---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-cert
  namespace: sonarr
spec:
  secretName: sonarr-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - sonarr.lab.jackhumes.com
