---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-secrets
  namespace: sonarr
spec:
  encryptedData:
    api-key: AgBug0O03nSuxVOib9n3n8byO+zDB7wmvn7betOGYvPr+CKLFpXhWUZuByq09cTcop0nnSU1pZV0mO+bklCRFrJ9+LGhaP5weeN+sO9dJYFY5fTfHcpRDQ1UyV8rmLYeNRcjtCo3On5+z1gRVW+sk/+dgECrpqP4HODGyWpIRfndBSZbql/jjT/1sE0loP0jlv/ys/8HPDzZ4R2whVdQ7nUNWV98EuPK2SO9Zo2o/peloZzdORKomQZzo3kYaxz4x0phL6TUK1ktKfvVIJmsnRy+TjRz0ln0/8bhfh2o3Q9XzC7QjFz4jU+J1PpH5E1+xoThnWGYUNDidMnxyya9GeVYNk1lU7kz3DVPyVfiZmEgfaxnmtUN2rbzUdT0WiO0w74SMKCiPRT316vq+7gsbu9/B6lzpkj4Pd6fn++bs9Zx0FuueC6ZRkUuFopCdWlofSuPEwerge7D/QgoVoiGujMuut+HwYmAayd0eOZXYQszrhLAwPCWMih+Ff7t6PKUrA79c5tBJE5kHI6kbEDpNNzUXdsNSm3hnQ6cWfthnDlyKPqtf0SGKFiMqhP9lbhv0YRfo/VclsrL/GvCIuRaJcRx6fW292yItF43vPglRt1WvlaiyHL/piMY0n/BNphntiwPaJP9JSX7kMqsIn4FY1h4xlZ5nSqVEF2L8ETIzCoEXB9Nzgom9m+Rb6do9szhZEeX6DXtnNGBbzsasMEbH9sr2hkofGcLhhKpNiraV1rq8g==
  template:
    metadata:
      name: sonarr-secrets
      namespace: sonarr
    type: Opaque
