---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radar-oidc-secret
  namespace: radar
spec:
  encryptedData:
    auth-secret: AgBLVHBJrZdNIX6pMEdh6NnDgh5cBayK48RWxaYduHg8GqCFPwcrnxgw/EtRwi0o0C4InlUhqW36YEGDXG+J4ZYpvtUOirHl05dG6piT1Vhv08W04TYehZ0iU7hMu1Ccf7rZH1d5SMXRfT7OKpJFk+KcZPC9h1B+1qEc3lb0pf6bLzA2Gyf4i5u7sGKszk0sjd/aOcdNY8CiC+IQIMK2RQhxba5R5UrUv/nAnKiXLRRpuAkhPlKHkL14375bt5xRh8OaFeoRVz0sz4MjZ4EK6m2UxXTPB42+RCHIRtLAtHZ6/wIM8C9whTygY/bNjoQ6F9veZB9SbL3D6m2Hsa1Wm5Az7Kq9YBcZI4+D01FKOP8jcm3uZ3tZbrOPuKmoj6fxsnJss0dpNCY88H4TRPsA15o16nSjNuNeNqi/5zJy1pOOBiOBw2tiZKFKFRFKj/L1qvUFTPyVxQ73UN3yRUCss/dGfMayGHi8B4qoee8jXQpzT7Hws9ngm8oVO5xgM24f+9MHU7GN63LWdB8pRDjBv+TVcyNcAu17t5OHQU8fGmg8ULB1vxvpARsTzQCEoTGblaXUgGe7BhFokyU/o0KBKXZa/NbUT9nm4bb8L0AiBJ/k+LC8EZMmaW1Zx5YpFIvABigbgLPuPJ5vkKtKk2INQcrJH/sHVYHFTiiyawmIXWutUa8Y9KHuEpVRGL74vePBd/GzMmBkoSG5ZS7exWfr47C4K3AVtV1n/YvH5x3pbUGOzLTKL0aULPuQds36SHKdSFAiZhT5dSf73sHlaMN15DVPww==
    client-secret: AgCVnQ6LwNp8+u1HQiQOpW6DE+DZQ3p4/aYdutSM2rfk6mTaNRMarV6QWMQqI6sVw73rZjh5P6ekk4risMBg812ZXkkveOSAQ30PgGO+caDbIGYAKS9OdGVVNBcdwYOjiE6LX58o5YGWgcdL6vEFojkoqEnRlf8y0FcQwxWHvJz9F5uXYijvjFZZjiI2luhqV4ocwSLvYqCFgvmdTbxRr++yasoi29x7XcqEQTMtOmxqulq5OhOhC4RDtGRXw1hgqoXjm9aWlVAXCDoSXc+Vq+CgcwNqw+ayZW9cQSbFgLZeIugktaBLetPpwsOKUWRwiwV/sUfcHX/mMwdu1PkhKiFmauRdrZ7/lYzKJUW/KkdZN3KmfGRWlIQaqDC8AGpxluZWJmpxJpTx5ZIZehEp9BNmPiJoC2Dxl+z4B+a1bhLwZ8YhnxstvUBaRkAEemLT9mFu01eaF9L3LiS2JkpT9xkS2KxUFhj++HC7j9OIXdudswizPgnWqcE06hqutTl7qcVJGW3Qx4E5REcFabopFs0cGCQuM9hSAMtJBBT6CyLqPI4B7zb4wsjl+bJswPmvDSjMwbtGNdUTUQEid4sg2mqPjQh5QgaJDhu+XRo/0T/nO/rotwysVbeG1bN+PH7SVpCxMaiJDM80WvGQIiuDtT2k2PiyEl1ucqvqwIUqCRoKqsDb5j3YVbxq9p6UrCSgURquedrS4oiAOAVClkElPIoF8evW1QS8n6M7IwsnVQLuhQ==
  template:
    metadata:
      name: radar-oidc-secret
      namespace: radar
    type: Opaque
