---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radar-oidc-secret
  namespace: radar
spec:
  encryptedData:
    auth-secret: AgAS4KNW/KUmjD/pdqWgxqQ59wgmTwNiy9RgRHz+8ZJ3wTMohPkSqDyf5WENRQCJfU9yS3IRFvUUypq1uIWZuUeXYV1LVXjDwsE7wkj10vyqfonmNR8aqvSK5eNSQ7t7TacjuSIw0TAaFx6ikBcDRX9E0YXMylFVlu2iFlU71L6XMrxldPH1GBULM78KbfbOkhm6518qos5il174xkZrgMI917eBmgl3skufOANWDqLJBSHoJx8fNTh8cBS8nBR4Z92qD2j4BvDCHn964+O1jdJnRSUwXZRFpJZoD1C808sewJZr0JwQQgMdcD2mW/av+6lV6fMzM7KWAaGe2FEolwYYZfs2wml1kWDzLIVvI2hH/YiolLPVREfhDy4PEJNG8fKFH0GAeusFFFpUHkmG02hpvmUW7inLx9L9i7Hop1fQq2dl9SYnOLsNvVsXOzdYC9Nj/WocuYjW7dEqxfQN8i63gtAoRG2dLNE0jgZ97tl6a1CwoZUYcTKXuvCD7TBslPGZmCs3ERVQCaF5LzZH682LKU+vscwqIRGOI9edixGkMPDH9Mc+LtYN2pS9WY64YA2Li7KTQiy9/Lu2T2rYHjMuP7Y0HwjdGRdwUS26twFSpUs+9pmenSYxl8Kj5cElp3OJZYwKi7ETAYM2UFohZw9NLotxT0KzJIyWY2j1a8LQxLLNrR186oC/YBAMGP+FQ/02BzOloPPtyrTwXZOJ2qnJMv+/oOut/C7XLRM9SqjM67DtwH/HFgTHfO3gW1M=
    client-secret: AgAwVDzVyBxNhH71Mtp8Kiz8OGi3m3JtGYAsq9g9CxeteBmkbJYM7XOB/6NcIwqHEkbeA5JHQAhnAny5E4GjrINQeL6wVodFamAqr038+41C42gOlM7qzmCQnohia50KS4Qqrix7iRfpzGs/XpHfdUsphMxg/FS1yVEh4c0lGtZis5M0LTnWTxTFVoL1x22P60DnY5h5XEFnB18w5c1mVh/ByiyzL7gUAmTYbOz4RttIEMkJnXCEbdM/kYaaKLfetvNQzeIJ8WNfPiZNqqHMZ8N3yvPkC8rep8mImha8mLdN/19pXp/cR896f1c5CSOoVI9EKLRAclvSblbMkNoPSlWPbgUxsiQdfTXjB8IFf02mKY/pDLmoQeVnjm1dVOUpoqibRJM49l7mQrhhl+zWb4GYAA0tl7pvzxp9B4eExq5y4FQ1T33x5bhogwo5zb/PuzdiKEYS6mNpBPaYqxk7jXQOqrJzxbmaPkU9Kw8NxRH7dMYWuwjp+pkFgkluD0Tn0iE+dNn38Ga6eAry8E+C6/LN9Ny+aYgVuyKtshv9xupQWD5bsx+AGzBDhByDSJx8ln/JBHjVBGhH9unt6Ath1NJxu4Y6jHOsFO6JkiRB03A8OUd8mA5Tk10TakzM1vLzSRHQvirqBC+DoaHrX5XPuPE6R9EtZ1PAtgh4ocnwbI3as4NiziYxeBeiSCrTkOmQqj4sPOj+gBZ6XekYyOuM/Mv2L6IM+PPmEi+/tqbEZFEyfg==
  template:
    metadata:
      name: radar-oidc-secret
      namespace: radar
    type: Opaque
