---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-data
  namespace: matter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
