---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: profilarr-secrets
  namespace: profilarr
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgDALMAchWJmYm0fxMBPi2Hfxw+4eMhjDRnY4LEa95WqwX+vRAZdfhTMb3v2SrGWpGhLBCjBakCAz+SEZYoDE1ZVnCDjTbziUNLa1dubZ0d5F1+oTD9Nuq+v3l8kL1hj1eVMZNCwDiu5/suZeN/Jh7uAGgdnMZ7MGy+xwiCgRloRRo9t9c3flUkWqtPlfhEQaFO4uUbjOjCUmOCMBl4M0HxCghf1Txkvo0HhLm8Qtq+Zs0Q2M/2PXI5vaquxC62ie/CMMzR7nVppTcYL2s6zJ3e4TgvcX94YSPVym6/aKJCqjFrz8yAvxw9WNm4y8aln2UHKdcUGxthIMLnMCwlsrEzdejt+6N08fMYdruFnbkdVBr752MGG+j97Sd47NWDlPbZmos59KeknVmpVgvBldg+Ly4UveXlYkovwJ+WBdhFBe4RQkz1NJx/pqfEmUcLT5E7etfDkj7YyRNzoHlCu5Bd8glaQ7sFf2xwj1lzhltXLyap7O0q73vuhVwS74cV1DEl5RRwLdi/N5SaYAc1WC1hLOTbobtTJaxF0uHjFDspNT3vkc7ZY5reaWJIEx0jU4ToVM8eJM35YXrjNC4C+3230MoiAzV5EXmvLdQXp6xnTsLXScRE4Kq7eBF0Pfb0eOuV0qs0QoEbSLDNJv7iv3yE1p5tvHotXKrOXRoLrR8zow1UV+cT9PYcFSLoSc0M4XMsMNx63xHc3tHUYnfGMecIylmVr0XE7fWaVZgfuG64dmQ==
  template:
    metadata:
      name: profilarr-secrets
      namespace: profilarr
    type: Opaque
