---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: profilarr-secrets
  namespace: profilarr
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgCoK0JJ5Y1BhQEeEsJRXZJnD5zEHyhgx7p+JH4tbehFMSXo/wWDYdXTntdWKKmTeKxg8ntWEKelVwQklYTZrlMe97Yg6QMEj394QLsJuHpbAbpSnWvKwGhkJZRmR/LE9c3/X7T23aoeyDsp28GIwAhyfTj7DnS5FtxI2Tn3dZLHcEOzfht+D8F/xj878/+9bQ3gA9UP+/SqfjmboCLr5pX7l6llf82GNiDPLbxw4NZzs1OhLwqbyxFrvCnfa1/RsmAwjWUbEanbgG2Svn7PVyom12g8wDCU6T200ssk/Pxl8LO7eFcoXYkS0A4qPqrbb/iYGdQtb/ZKLu+l18nyI6StwzUiDzI/ktJu3CSu2kmYbsA/2HETkRVlDdOBhdCQt3jwm6hzHYihx6Rqxz57JyQiMWpdOTOdyXm82EJM9g+Mw3cQ502100GPNZgJ4TD/1KiFN4FbOh3r1rfNUe5ibHoJmzaPafBhIvfU4tmH84g/nbk0KBNNUcVbMRDN9aVEodydxfHTe3OM6T1UghUjv2GGV/f4r3rRBVElkwdxTidsUWojfdsPY3VCN+SiDmSJ5SuhRu8wQmASh8GPtS0ikoOt6CeMoMniTHh/bvp3ZzyD/B5b5WkLgcAZvMmxippkGiWVe+KCGkByuBBYWN5bQCPxRpZ1BE77cEEvnlmUUg85FjrUJIXoo9COGOrFq4N97Xspj6O35ybVgWc/sfnR7qsRSN1DDaowVyWGHew5JzPblw==
  template:
    metadata:
      name: profilarr-secrets
      namespace: profilarr
    type: Opaque
