---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-cert
  namespace: jellyfin
spec:
  secretName: jellyfin-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - jellyfin.lab.jackhumes.com
