---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-data
  namespace: changedetection
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
