---
# SealedSecret for Tiny Auth
# Contains OIDC client secret for Pocket ID integration
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tinyauth-secrets
  namespace: tinyauth
spec:
  encryptedData:
    # Pocket ID OIDC client secret
    POCKETID_CLIENT_SECRET: AgBrttIXm2mZ9K/pb9h3XPQD8WVO7RRJhAbXUCLKVAP/kEvsP+E/HmvOX4WmfEdxhMiv5jEPByDZY5p7u2oywsZbX38qbuLQnE+ewkTS6i92aPqYZ3l6jxtjWs5rB/ZswC956HNmj0F916Gu31+pEAjI5Vn7M+gDa6o7E9yKkU0q4bqdWj1ML+hV1vBzc4iE1cJ22TGjhyAX6u3Ab0R8UYD6w9QZJcqRCv5nI7SjSFFiFJigBW3GQnoI5pPHhnKjhGzTlj+Kx/wOCP9YgJRfDQQHibUCh67cJedprK/Wy6k/9UTBFWfWgUoIbLV918IsQAtJRszp0MH8CU/g1Gpmk1aVH1irMAUhKd2M9F/3jdrDl/6gy2+OmVgoRBCp+P9vBfrXUT691xCP7ZLz3i5NTGUDxqSb01X7ZBgmmNhQYdkGww/h6/G5LO8Gr457zyYa2+y7Sqh9pjVM/JcR2u5FiBHZWXez5guygvj5DynN2obqEuVncCkbKUKAN7eWZ/QUGLk4BIjII1Ra2zmH3P1T3uA0ON66gzTiV8qtf2yEa9G+/GvxI3gFndgcWDt0CA2kJ2U5IUcD1stO5Jd06JyMjWPTmLsKkN57S06HdeKpzdmwd9ZKyHdCJAXRojzXUB4bzTh2ADZpfZYNwYBLNRq59ME4WcUnsP2CLxHnhpHn18JV/fg4V7OK0UyBO6/ovWdCrqe047eNoOeawt33BxcfTUVe3S2p1NQLqe2fOvoZYNtFQ==
  template:
    metadata:
      name: tinyauth-secrets
      namespace: tinyauth
    type: Opaque
