---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headplane-data
  namespace: headplane
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
