---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headplane-secrets
  namespace: headplane
spec:
  encryptedData:
    cookie_secret: AgAd/+EZ7V9LIlr1S4vHuFcmksjglAapt69A8BLRcalNbYYeuLbryAIcan0VW6VUSbJO2sYkkR9SDhXJnv14dHs/PTRfLDWI4dJgWgqn+kHmONsT5KoQIOzyFTicMwM+vNj0iue6aRtf+pDhDqAp9+Gn+epX44z1BbFEWHnhGEfyL+g/sX2DGMmnkeYvg9JZnPtqSDNdwTZB6uzbalSkwZM/OKnwDUkZT/8d4xs+r86fOSdCGM3n4IN5leQNg48ZkW4q8Hv8+5IY5lukJLbmwOzKWEyjHJ60ye13dq9+xqKAQHC3sZHSxWQvCb9D1w3Nc8nUgYkdlfuS8RtyBuBTSCjx38DHMQcKwNzuzVW3YtG8SjT2yUPLJM4KHANVRu6zNjaJ1k2yTlMobJWnKO2hnKcL5PHO0qTGdUvY5DVW2RTD0VyeY/W4Ec9jQt02kuubrR/VhsCKsDs2vjrInxobM8W8peNaOJTpmP26PGmQc5hCL8gsvYBuamhjK1FpeNa4DL5r1WFFIm+1+J8T7S5Q0iVZwGwet1w2WqbmGJotABgGV6Z1xfEyEjtGOdpzNigZoAbGI7FJcjEnxnl020Uo61vT+QX+mptJgBVyq7dtzacd+etBBAkAzU2bnipoo6ex5TJFqCmQZA4IYW6mH1JMWq53sCET9xvztTulINLd6FRT/FYmWf6HkaM7wyiV7kmpwdqNeHb0HcjhLpyDJDmHCBV5zbkbtF33zrvuxcmUH0gQ1A==
  template:
    metadata:
      name: headplane-secrets
      namespace: headplane
    type: Opaque
