---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: headscale
resources:
  - namespace.yaml
  - pvc.yaml
  - sealedsecret.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - certificate.yaml

configMapGenerator:
  - name: headscale-config
    files:
      - config.yaml=config/config.yaml
