---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headscale-oidc-secret
  namespace: headscale
spec:
  encryptedData:
    # Pocket ID OIDC client secret for Headscale
    client_secret: AgAWNMFV/0aoU4v+r61xzu+2fOKOB5XyfWhMkx47uNsa4dmnW254p0C7O0UdvAimJeQkFl4JCV8j4qFN0C4hfa2geCN+qOPxQbVh0g7Sv35jQgngziK5l8vKuJGsgTDgS9mDoeU5QlVmEXvvSaHZd97vhCss4gMPQu2Q/qg3giRCHNn0bSkVtPKYU27jkgCVh8umKVVigz8+fc1QEk1KI/vHDh8K24JOuNNrzsVM7Vc1GLb6HBpF4/V+dRHQRYFarHW/fyUm1sTM+BerdU+dJ6IclqaEcfxFC9jJmBIditsDKAp8YseVvw7hfTNtIfRqvks3xq7B4SksSMsODyC0WB6tiw+hiKUOxoScU0cAkfckU/xU/XZXbe/9VDUVI5iObrwb4APkGCDyyDjd22jBtrXyi+koTlWGYIAnZ+mxiU6MkrA6t5+OgSzOarp6oCNZT+9WjtVRiMGcI4KWROuWMf4izQjQVr5uFDC9RWK0X9Jr2xNW03lPMLJWyz9bkFt36KgRJ0k3D3tOsahqDNXD2goCWUWnUmjFow/i/t4vyUkn/hpVwPUlilE4Xl1nnNCg8NgteWu0FHzPpubwpzMGst2DiQLNe0TbAV24HTZ4qvYY/Ikv50MM0R8r4m8z74j8JPxztCngWypZ3CfM04KrWtvjPtnNw2AJXhrQCX2sVu1jlnBf80s4l5s8nAMLW2cyryxrk+OmPx1OzSauuf/zpmM8b+ireOg1lz4Y45b4QB3VkjXFN4yoObPFbEB6mA==
  template:
    metadata:
      name: headscale-oidc-secret
      namespace: headscale
    type: Opaque
