---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lldap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/member87/home-ops.git
    targetRevision: HEAD
    path: apps/lldap
  destination:
    server: https://kubernetes.default.svc
    namespace: lldap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/volumeName
        - /spec/volumeMode
