---
# NFS Storage - Direct NFS PV/PVC for Media Applications
# Provides shared storage from NAS at 10.0.0.9 for media apps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-storage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/member87/home-ops.git
    targetRevision: HEAD
    path: infrastructure/nfs-storage
  destination:
    server: https://kubernetes.default.svc
    namespace: media-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
