apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    chart: pihole
    targetRevision: 2.34.0
    helm:
      valuesObject:
        # Admin password set via FTLCONF environment variable below
        adminPassword: ""
        
        # Persistent storage disabled - using emptyDir for now
        # TODO: Set up proper persistent storage later (Rook Ceph or Talos-compatible solution)
        persistentVolumeClaim:
          enabled: false
        
        # DNS Service Configuration - using LoadBalancer with MetalLB
        serviceDns:
          type: LoadBalancer
          loadBalancerIP: "192.168.1.201"
          port: 53
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
        
        # Web Interface Service Configuration
        serviceWeb:
          type: LoadBalancer
          loadBalancerIP: "192.168.1.201"
          http:
            enabled: true
            port: 80
          https:
            enabled: true
            port: 443
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
        
        # DHCP Service - disable if not needed
        serviceDhcp:
          enabled: false
        
        # DNS Configuration
        DNS1: "1.1.1.1"
        DNS2: "1.0.0.1"
        
        # DNSMasq custom configuration
        dnsmasq:
          enableCustomDnsMasq: true
          customDnsEntries:
            # Wildcard DNS for lab domain - routes all *.lab.jackhumes.com to Traefik
            - address=/.lab.jackhumes.com/192.168.1.200
          customCnameEntries: []
          upstreamServers: []
        
        # Environment variables
        extraEnvVars:
          TZ: "UTC"
          FTLCONF_dns_listeningMode: "all"
          FTLCONF_webserver_api_password: "password"
        
        # Pod DNS Configuration
        podDnsConfig:
          enabled: true
          policy: "None"
          nameservers:
            - 127.0.0.1
            - 1.1.1.1
        
        # Resources
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        
        # Additional blocklists
        adlists:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://dbl.oisd.nl/
        
        # Monitoring
        monitoring:
          podMonitor:
            enabled: false
          sidecar:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
