---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-cleanup-daily
  namespace: longhorn-system
spec:
  cron: "30 12 * * *"
  task: snapshot-cleanup
  retain: 0
  concurrency: 1
  groups:
    - default
