---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-data
  namespace: crowdsec
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
