---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-secrets
  namespace: crowdsec
spec:
  encryptedData:
    BOUNCER_KEY: AgCvPssuFxFXPLc/CUZrtI/vu/6kRcU1mPl1sCPF5DNbXQQEMTrEsgDpR7vD64ULd51ecLnAWShDBVUMA18TkHyjIDNpqPkiXyqpH8STA8tsH1AHm04v8/4I1g83DiES5dsYdaWkYsl9XfhVv6bs48IZ9TuFhATEd199C10EjsaSHXZixLtYaVPmrn2O5qivPkx2npscPwbaQkD37/FbLp0LS9J5PNkQiaGoFbEEmfh2FHfO43vG2vhy1nL2V30ws3Yu0WLRsfQ/FeoCXvaJM7UD6OjzMHGjKTQhoE7k6nx3t5Wl2ZSt1QqxsBtRA/hMz3xvnQFwi1Eb/1V2I4xkRpdiMhuoAZEDKI0o3AA8tCV7ICNNhq9gG3qgzrl3aWeXPc4lh8cCq5cjnlXZg+LStTsGWwle80FBhD+YXfd5WPVhnz30VJXe9Q3EP9MvDEraKRnSYAdS4JDYX/3puUxIQxE6Ly2wk3k3L7iDEZ8UBrzZeQ/1v+tRWAPr+oCc4+GedauF/VjHLPjMOXVsIaYHskxupqe+N1vKYG24cLLyLZbyEUl7CbPnTy50Pe2NEg0vF9Z/QJXChQneMUSMBnEBBHeqYvvHaZ7sazpCHSYNifuBUh+2tcog6/dMqb285AiueebaaoKfqS6IbTrkrvcHy4gRlrbF3I9S9v8VIFFHaCYsVeGkGurZLyeqtADFYsf8evwgmJtayLZwGI9BCosBaIvMMmhl6bxaOm7+y7CRsdOJEhoMaC7z7plMpSYkqA==
  template:
    metadata:
      name: crowdsec-secrets
      namespace: crowdsec
    type: Opaque
