---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-secrets
  namespace: crowdsec
spec:
  encryptedData:
    BOUNCER_KEY: AgB3RBck40MbCtwhbWEguX6zHbVgSWQSYLSqKww2tfF7PgyZsiUGN1tQOMkpKZs0+AA2uo1vgXpH9TPfm4BVzOmTbrfKy/Tv2wu1jH5d/USjJT3gra6DHfBOnC3D8+ZuXP/Afu3TIKIw0dCIM1Unb009LHGRfQaPcTFiS9fXIoSl3/rbqqdx+bU/pdvt3BePP/GsrET6qRPrZRyMW2fPLTLOGbTAgRxktUCa0k8jhWRj+9bfcS176z6JYxI6xpBw20P5KsOy5KI0sitY8H2IM4rndTQr4+8ClMd2WGwYaghYc4gYR3huN4paxHd3BpI3vVbR5waf8YWpZA6SqkqUhIhibxwpMqTT5aiQjdNn7HwWB2mlK4YsWJpaQ7wynK2KXV95UoufChs7PABioU84cruQGe0mL4X+gzmaRvOwMk0d5rA+qL0ezaUBH+DURwLfO52wZLj0eiQMwDzwk4DfN+VUcP3mfMIQfA5tandR27MzdzhH4Jx158d/lsHVecyV3uNA5pZAO3co1owvPR8khFBe1kyj/0simrOve7mAAIPmeI0gV+xoFZJzErR3gJZ+YMyNJvBHoMSHXe+dsD1I+s176Q7T7/wd2XF6hgwJ6qwtB0Wr9FmGxJvz3/hReTxZ7qInlwfdIhchWGW2H1pCVSqS9D5L8Y419jMFSREDT7Qrsbd0y5XWnVVVP8rxBaAgyot3Qb+XDj24L58TtbFU1o61MetmkVja4rKBvJJyHentodwC7iZXd+qVyPCi
  template:
    metadata:
      name: crowdsec-secrets
      namespace: crowdsec
    type: Opaque
