---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crowdsec
  namespace: crowdsec
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crowdsec
rules:
  # Required to read pod logs
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  # Required to get pod info for log acquisition
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crowdsec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crowdsec
subjects:
  - kind: ServiceAccount
    name: crowdsec
    namespace: crowdsec
