---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-forwardauth
  namespace: authelia
spec:
  forwardAuth:
    address: http://authelia.authelia.svc.cluster.local:9091/api/verify?rd=https://auth.lab.jackhumes.com/
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Name
      - Remote-Email
---
# Fail2ban middleware to block IPs after repeated failed login attempts
# Monitors HTTP status codes 401 (Unauthorized) and 403 (Forbidden)
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: fail2ban
  namespace: authelia
spec:
  plugin:
    fail2ban:
      logLevel: DEBUG
      rules:
        # Ban IP after 5 failed attempts within 10 minutes
        bantime: 1h
        findtime: 10m
        maxretry: 5
        enabled: true
        # Monitor authentication failure status codes
        statuscode: "401,403"
      # Only allowlist localhost - real client IPs come from X-Forwarded-For
      allowlist:
        ip:
          - "127.0.0.1"
