---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-cert
  namespace: radarr
spec:
  secretName: radarr-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - radarr.lab.jackhumes.com
