---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-secrets
  namespace: radarr
spec:
  encryptedData:
    api-key: AgBZ+xdPkvA2FvgXVoZSjyug/PAqVJOd0n+/I8Y8tcaHbJS7APtuUyyD7fKNS+6oUK7jqmwU6zPpMEfigiX2LR00Y4M2slih+4QmSsGBHjRPdqVB9EN/TsowtS4U9kK4zVDUFWZNFrgB1Jrma18SHB1v7X+6xMTm9eQPuect3nG5ma43ku0HiCbSQB8LVetr5xPUa/bvcvuxwJZc2SS2v4b0T27KKia99vXU+xe/lovhlmqf3jJ6wpU0SMYyyjJrtjKD19HEP6Psuqf2v9+mYW4zoBwMcAOiOnksVS4ugGuaRe+uzAGijeHVVHCguTFMUvofL8DBidNFn5zWR3FV4raNkwOUW3OpR7x3Y231Rfiw/afl9OqJ/eDoNI0o/h4s+7YZKOqVDSqAX7bzZB2pB431lGmcD9sv7LYjjuJGba6hwcTpWrhme5gO/0MFUCTrdoH05/YcRDE6oAByVe2ZMfGOr71JZF92ddgA3Pv2UkM00bYRudzfLGXHYyyHcll6RLXM27WsSUn9MLhdJMnskVvERHJ9DrRyu3zf0g2U1D1kRttV9NdSJVciQ6AEwZeCUibCV75Q4Z8VLilESMhKzBdwwnFXAQ5LxGC3iFYhasmovECdg97ao2kelnFjUfcDzLdRmeuHO+F39Du2VrRhqv/VsGVM4hTaDfqOLn5nqCKKjANTFpM5FULKC6JwVRD2QZ2gz1Kmbx62lDgTy9pV71qPUwDdqN1F8lIV1jPf3z2k4Q==
  template:
    metadata:
      name: radarr-secrets
      namespace: radarr
    type: Opaque
