---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trek-data
  namespace: trek
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
