---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trek-secrets
  namespace: trek
spec:
  encryptedData:
    ENCRYPTION_KEY: AgBd77zGv4oowaeDn+I74AbTxLdPUIcFg3Q1p6aQdalZKmA3qe+5m3JFKP1oaB3c/ue+gO9PlwqZSwKMfE94sVXHR4EWGFNvdALPLdc+Sm1JJsWECKr/QGnV4JtlHPHScoqTmfigct1kxXpXjlIoUt0QnLEEgP3/Wtj3ZGww23taXWmkI5tH5mi5b1SbE23jCkG7Nry4Z+VRV+releoLYI3ichfTAAGoO6JLvMETlg7uIefI2HO8nOzis6w4XxDHcm3rHZPYsljCt4G1t+R0iNyI1AqBHEZxQoNe95UEmVFHvr6bvV0+aYPfsizbDQwR+PZF7W9bEkkQKyQ5gowuhJb3izHdtVElXKKR5VmNj+FU1hHDRg2wl7QuXhOjOZHgUW8sQPY7MY+wGr/cJ0JEE5LROI4wL5CVW+q3PsSGJS9/iGi/gnb5WcTuGeRKt0fnjjxbqiTwF/R/ikEYKXFJWYXTCCaYjHnDsvgHNoVbZ81Nz2MiScaL27Vsfn7evRpQHbIeqbKHB2H3YBdGQxB2cPjOHrrYeiakRRagNE6eP/OXMNNTS9SYK9naaZ9VOYpyOS7D0bCSgnkIxChWtK8rFjCBSqsLtde9C7IomNb6ZdCAqhrWAS/6D7VI2uqbTXa4GMQVUVNsu5PHJDbGGMODqwQdJRG5MDXlU0xCCQd4JCDd3qs17ohPyx5PyzwdDNu84lrBIOzU1msZjI2ZDg5PSTIbCZ97K+U8YfXXBHdSNa2cHHug6dwCaon33uPVdl2xWz7rzMqm1gQmDhFZj675TrzD
  template:
    metadata:
      name: trek-secrets
      namespace: trek
    type: Opaque
