---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    TS_AUTHKEY: AgAHoqXnjMnd5rExuuovFimcJwjS+squXRyt84iOnEa0/WKJo5vuybAP/y4yD4kXGhAuGuZaKpv5teGUuhiXsmC/zi2L8TurbirFpN8ITli1eM2GsHtJTaGCIXWJYqqqrZGSPCflI1UfA0DM+s/dKZZyygdvcgXbz5ITd5HCtA+0pOuYbqNmkif8+k6j0ZrYEFrJ285EnDBLR8y7btS+5+i25TO4LkahFL8DupU5++JkMZ1Br0hQpFVb3L6rhgXLWCj9Z77GT/YMzxHqq845DM6KyhnksOHJUUd8/iEh89PyDUgs7aR5+ZIw+5ydwUv23cjqLjbMcmJD2cJlC2Hv9uR5968sqEzFA7xjO/sfVFfDi2yF9qP/mRk59tAJrBXFzfihgZU/aiBF70esL5iVe3ei3Yc49/w/VXUwK/260loGMuG2BH5dcbPBPTB2JzsyS0TnuekZ62+wEFAOZjXKMW6NWu+n/zGKXGOgYI18GoNpnRfx2vmOHUAWKWrTEkekxyThQWgwlr5Eae0HC0wnbEMbi/3QpzgZD2oDhdFAMZ41d7M3MqbphEKCQd5qjeF11Rz/3COAZaAkjAfVXq5lrF6H1YL1kNILGyOqgHisyEjADxucg4H8QQdZA/pjyVz0eoO6V2qtbhR5fUZbFSj7OO8Ced09G3FGIVa720vbhnPDKXMW3kz0S6tGVIyv+mhPY894q1UGhn0IHR/6AngvSnVLiPsknpt0fKpNzscaQF8jKX5qlrjiNdYTKK/bDcHKnwbzhetD+JCmFszKPxdF7g==
  template:
    metadata:
      name: tailscale-auth
      namespace: tailscale
    type: Opaque
