---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkmk-data
  namespace: checkmk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 10Gi
