---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd-cert
  namespace: sabnzbd
spec:
  secretName: sabnzbd-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - sabnzbd.lab.jackhumes.com
