---
# Media data PVC for SABnzbd (shared media storage)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: sabnzbd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
