---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - sealedsecret.yaml
  - sealedsecret-oidc-config.yaml
  - ingressroute.yaml
  - certificate.yaml
