---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgCXSd5eoUVLAWfn8TnaKtxh/WC+s8HT1IpOHIAjQ30cdboWfzVLgRr8sV1ziGKOw/nndPjorHx+xnRs6/HOZPS7uG2JgJ5C75DNPgA+qZaEj8UkDz2gDmD7PsRVTrZRC6hJ0PanyXOWdKRBapR/zDofR5hZbni1u4BbhUeE1KsHmdnaN2h/rYMlfjZwDXENnh7Uedf0IBU2typewMzwVxealONIAMXzSluJV2bOu3EuUixwiDG8d43uqASJ/eBQ/eTNaYtOdfu1kvWTOua0gv3Cg4ypMuCIct/+V7MSDfKR8kpY8RO01ZC6fHdTWtR6CpolsLsvmaGrKQD1wT8a+jVIZZRKLtb7W0bkj7M8DhsROmPvAnHzTfgmgRoLlvpdZckV1O84sotJ0OPmXFcbJl8fx2ehVGb6knHMQT4nDuke6D7YxCdLMsbSpD5fE9O2qQ/GYKLueBphW7Mj25+8o1K+SaMIUK5kvxCyoud5sOnYxwareaRprC4UnE4ViKetzVljFdU8CYdY37uVGz5XHCLtbvRhX3fsAdmvru5pCmMooiJ1xR68vcB6Zsl1AlOJwbXQkUUpGsvmn38Wor8Hm5ozHg9MX8C9d6xk7m8wkOGPrjYOtJpuu8DDgvuWWOtx2k/oFcmqQZYenHmiRRdnX6NGfP42pe6vZ1q5TUE4MIYbYVM2Pl4I8EGOrYslkYqnIeGLO8JiioPdB8TDitFHievcOeicb2T7QMc8E7SHQZOMvimGOUhKwa9V
    DB_URL: AgAG5Xbij0vktrbVdwt5EqC/iwJrbl4ktqM5/LlCVyQosduEanUcf11LP/Bdut7944ST3EXlz6I2PZ9gxUZ6SejIx21GqlsQRfmRpvpx3PGByhuvxJVmoo85ZMTJ8zqQbUG3gKh0AcVOD66cjJl+5Q5Xfkepl1m0fUbqsrsYKbFXlVYfEvNAWwXkkX8eLqPPviV+UjA5xjfP8BvWR4AW47Ztogko0YOHNXNOs4Zjyhfhns5qX4OwHznCjrLxYRPafnJ37kRcaovPGuY1rjZAciCsRaDj2NCQ2hua8WIBXIg9nLBWJtx2I52s77Z518GKwjQrvMbbwpXoLNI+90rAi3BfglVe36D85h3f1rY0JT/Q/YwLhW9p7/WRdtTEIvWgU0czf+rwBgtS7LgX/aGCcHXrc1vru3C2VtojUUWGwrGbRrIAE6SnCsu7A9k7yHj+TgukxEPUzENeSLBH/ym32G44MAevLeYFHAAk44w1UpLSVpRR53w/y7Xdnuax1/4xmaK53pzVq1fzXP2XhidWl3xFk0qEX6fkBdKTU8ybtPMYfnXdr8mEidhRD51T4O7N+3Q8/wpCQ4ohKJht2tpm3wVzFxHK6i4Z7bg36ff/Rt4K2RDwAtCGZrKsVCkSqVPwnEnztOhkBPwFwRFsrzVOOA8aHLdcSzPMBuhClNKsG6SS5yOFeZtJa/jY8QVKdUgC1+JRPiS47EN/ERRYqA8/pKKiTF3ODilFW6ThYNCASA2LOCP2C16MzMRtJfP9jddWkB4b0KLVnNTQhnAGIi9WWGgTLnpc9KRjGjVGXtnIra7etieOyuNz6Dou/b8+6f2YaJpX7tl2O45ilRebFQr36n98
  template:
    metadata:
      name: immich-secrets
      namespace: immich
    type: Opaque
