---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-oidc-config
  namespace: immich
spec:
  encryptedData:
    immich-config.yaml: AgC0mDMHMgPksD0//tRIRe0cL96mVwit8JA/faSqFmbPSfJhLe4gVr3aIjAKowj1h7FgvpUyHcxyYjCZiLzcgY1P+OsMAlc+HWnIuuo1bZmVmXBrrmpJd0E8mcI9ux646ny0jc5NYgxExVaOXD7Vjr9YODeXtKZl2Ajpk2VOXg0baOBWN2fAacHIw6XjehTAzdHYrqf5rXiU5f3wcUTrTjzCOBGzDKV3zy/9vfuo9fhymk+bdy5PLor/+Ws0KMgrFBvwwIiqwZCWd6Xi+a7gTCuruh+cFMcTCp/ZYqP9AgPKi3z0gsvlPKzVziJOA5aJg+MV6bLFUat73rTbQYNq/HNREWzpeGuINooBqu5u/y3vV1qLbDBdzJ0++pKP+3RlYCo2UBZtQWy/LoLBCB7PWPF8B9W0nkinHbM+J6ymrHiG0IPZjVxcWTthIj411yRiitWtYVZaz915pNi5C3z7Wmz6b53UatK04kBX/KAhG7tvPicDMTZfwbL5BJfbMmFmB3FCmR21p/3dKkbNxye87fC0p+Omc11jSEcDIf+E34k3HRGSa7fAzKCMvQ5pTDgbVRai9LRyHabMZwfetS7nJxnYTZsRN8gVORcirsfcymdHoAf/hqei9emi1V92WsfQ0t+TljpBLACRtWVMiY83pqd6FEfWufjVZP1EPfVSb8iJyv9yBmFXqyokYvHyHQpu1z2mnEMbiW/sBfWUzKd7Z74yOf6VJPrG212RiHtb64Ved6P82AFMTABzmBJQMXKpGlEo8w4bCpnCFvFYqeHGT5SE8aNo0+r97Py1UCbFx9nUDDoajiRljMB5rqeljD9YU3EycVTNYvW11LncGxo9IPkO75w9nNp2k/7iR4lMmX+7BhDh86mqQl7QTliIwxNv82RAQuZjfcLiTSUPKxcMACK1MI85oDPzKLLPx/Vm7/FXZ0k+yFsNXYvToAbC9ei3pcg97da8QhglZucDSUk0U60i2reIhlXgjSE5L9H1YuD2jLnvHnjyIOMX2xPkIaHYz6DBOg6izDzAIsFUZ9mc6cpP8GvzBiqF2RagGmiyzUpY3zWdK9HzSfa2E9o0CES1eozcpFSd1ZPpt16L+uV17jtJsqd0tP+JKmTBfqkbLCAl83qM3P9TnAU1GfBQf7RthRB0IgUmko6gH6sS+Nkj/eINN8RjiESY9nCX2tBW4d5mhkjiPg+d4tR5uKbQLLgokdpROhMG5oCw8EtFz+RHWOxKocJ3t6YYTCCgp5vRFmavlrBmGWxpu4+ASw2pmdQUcfhs//lpWh1ijlLXmMZuj3VqqGf2VeI3HwZ+9xHa7eyjNQrmnXvIJ95cBlpvUNw4ru2+Cp8w4xsuql6wzl3BxxJQ
  template:
    metadata:
      name: immich-oidc-config
      namespace: immich
    type: Opaque
