---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-oidc-config
  namespace: immich
spec:
  encryptedData:
    immich-config.yaml: AgB2cqpvS+NQ/l86Xc/SUextoasVEuail0CFlO9veSTT+7eW6UK/1mXtJZlSzS5uS5+XRDlK6gcxdDjN2gJp2xvQdWAlt4U1E7vUA3nGbrNtzpsf9DKFLGhrb1FSD3YmHed+mrn2iIdGdGM94f8pLgyiD/dzuqO48JqcmFfyt3KWcHjk1iifTFq43JdzhrFQCqja2HM4Q9iRx8P617w+6cCk22enMg5RXKMceSk7HmbiujspI3rTAnUzJ2wCOs28LaC4P75p/QPCLkA0llrv4GyApgAzt6JSKXPVR25Kev8wNXvRjiluh7hmDXofpoL6sGEXdb9YWSJWDRd3Hgmh6yOci3kxJHrTiUWtKPxBByldZTb65t3LduL4WjMnjQetj3eRX4O9O6bQvcI04kt5dhi+mcOPSyyv3dsQEXAVCPReQ02eq/13JrAFuagXPL5eprRe9hvtX2GZOrgQ6F8hhORLLMafzLCG1UFnrq3qaxcNtcCfPzQmsIzSTjHjSCRp23LuZY495SmHr5cY7ZeoFTbXgujxLpDNKrcouFN+1dEh4Y0G9+bqU4v3w0uzL9dSvA+J2W8SCcf4ckC1PtoVlphLC95VdmyGL6Lj4bx8nalDrWCAzKvV5tLUiB84Rpb8mnSGmeSC8Vw3OiM7sSfpuk3uTlDbnSg7OpdaBT01MpoQ7qW0GIyk166pq9hxvqKqYbDrGZKpYx+EeR6yTiHkxQxgDt7BV+AlkS2pN7z3XPfTuFGvWfwo+hAs6xMFRjZAS74wlQuWD+rKmRPPr/J/o7fSNs4gbLoO8skvry3zZQwaItHbxGQaGsjv+GTUnBjQYGxD2aoW9alohnjTMjneTOfPZ+J/bZwi5T+6XJSHx+opYi6YS8Po/kfZQDFfb/0qVIAMQTQ4QtP8QAFT5ZpbVLjLzUTqg6iGdzYNp3ft1hfJ7ECuFnXBu12yAkBW134WZdjUIfDwAs7+YVO1TLIth7SNTmGQUB2yj5E9S/kAh7AGr3UtawRfFnlQvkfBEoER+zSJFVmg1Kw0Abbkqdn6+SXPbdgboD6GCfbN9j+zazJe7wHZvkPn/5eTOKTb+tno/QOHlPGkIoJiD9kIaNOyNcFhs8a4Zr+GlbqWI7SWGTve5Xjo/5YEb6X7gpO6AU8Hjda/ShAvWaoaARnZ73eXNd9PPwqQ2N0rfHVi4kRl6/F2hy436H32aeumEsTaEEd3fqtF5AcScfcJf3xiLgS7rdC4XpzX/BvEO8XUZEoTfAzFbxbdWAwON0PUzX2iw2ls4F8Bo5mXvfMZVkRsb9sJilOMTgm9jph3cCOllSppt0CfWJw3SW4rWju+CarGydEevvnKi7kSij57aSOXw8LLpg+gIiwxq4aMAha5LsMNByJfgsYMnG5cR+1xi+TdM+yVWd/O
  template:
    metadata:
      name: immich-oidc-config
      namespace: immich
    type: Opaque
