immich:
  controllers:
    main:
      containers:
        main:
          image:
            tag: v2.6.1
          env:
            DB_URL:
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_URL
            DB_VECTOR_EXTENSION: pgvector
            TZ: Europe/London

  immich:
    persistence:
      library:
        existingClaim: immich-library

  server:
    controllers:
      main:
        replicas: 3
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1
            maxSurge: 0
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/controller: main
                      app.kubernetes.io/instance: immich
                      app.kubernetes.io/name: server
                  topologyKey: kubernetes.io/hostname
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/controller: main
                  app.kubernetes.io/instance: immich
                  app.kubernetes.io/name: server
        containers:
          main:
            env:
              IMMICH_CONFIG_FILE: /immich-config/immich-config.yaml
    persistence:
      immich-config:
        enabled: true
        type: secret
        name: immich-oidc-config
        globalMounts:
          - path: /immich-config
            readOnly: true

  valkey:
    enabled: true
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: longhorn
        size: 2Gi
        accessMode: ReadWriteOnce

  machine-learning:
    controllers:
      main:
        replicas: 3
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1
            maxSurge: 0
        pod:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/controller: main
                      app.kubernetes.io/instance: immich
                      app.kubernetes.io/name: machine-learning
                  topologyKey: kubernetes.io/hostname
    persistence:
      cache:
        type: persistentVolumeClaim
        storageClass: longhorn
        size: 20Gi
        accessMode: ReadWriteOnce
