---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frpc-secrets
  namespace: frp-client
spec:
  encryptedData:
    auth_token: AgAmOapQ8TH4nriKPjKOx/gYKMBq9035qp+dcKxr0oLkNomuiimRNUMeenhLISIZqZanf+ALJDsjl7yMIGeAtXiY0fb/1KUpxPT3Ce7zjStEFnIQQpdr8TVPwAk2mqb/nQDYRhyY7wLDJWv+MICRIzk7A9SdRR+rLRbQCeAMRy8F//sTolQYr8YC4tL70xpec+OL45FA4O7AdDoS1BUaUmHx74mBL6H91I0fZ0F2V+JCeoLrNCWYX/eC+skTCP+DxSViWy9455D2AchzDkqLTy8wsSViFGi7iYoa74AENdfb1FwAz4w2lqJPv6bn/NGTqOi1LOjVgRRFzRfmcBg1vxi1IP4mmbWJ2dKiFEvds7QqmnBAGyPbWfkFEBTu9nCggwo2MRUDhle2CK4h/zHeg5+AtN4HLqREmaorBhSzyaaudeL2KM58rOhV/zPQe8sGHCdPd8IiUhMFbUUD1LLBV1jrDTq+Bm6gnid9ffO5ofRXSuWFQnF5r58zihr+16JtCPGNBK8hwYTOkqP9YvDGNlRhtA1mgmSTWxr8oHUL5bIIO01DWIpfhqrbq69vs3pUe1faUlzaYPx4ZEF88ATRhikkLPdje6Q+eKPM6IMT/jT8QLNYyhsyErzdD1ENfZJo21pE7hRirlogxIyXG2io+JWWZqFA94hAILKAkZ+iys/zrsEQGwcPdv3/GUw31Ev0zB2OXxauW5K9u8LzgqRx37b8XJV8lulgz1T4iPI5dccoL2IS2Q26wHIzXlVHZKZ63i+7bz9PknCKNRw5UAhLCG8c
  template:
    metadata:
      name: frpc-secrets
      namespace: frp-client
    type: Opaque
