---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: weave-gitops
      version: "4.0.36"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
      interval: 1m
  values:
    adminUser:
      create: true
      username: admin
      # Password: admin (bcrypt hash)
      passwordHash: $2y$10$PwnDhPoCUjv9atuW/.Wsn.srI6U899cjZ8EqvaWUf7FM.0H1O8dsi
    service:
      type: ClusterIP
