---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-cert
  namespace: prowlarr
spec:
  secretName: prowlarr-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - prowlarr.lab.jackhumes.com
