---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowlarr-secrets
  namespace: prowlarr
spec:
  encryptedData:
    api-key: AgANCvA1SsviLwzPGqa0J2BbWJDRMXuOhA18AJQMGxJOdMii8vhwptPqEcfVy3ZowhV/yzS3GEtrg87f6317ljAGaFUOYlGX0Cwu6Hh/CCKpUf8y/FcYo487a3FuRaLGCc4nK0dLUtW0KOrKgVUBSaKR8j4tQGqotG08+0mBHPixDD5rWPajMWXl8PIdUdDtcMWPO5MSli9PcUTttETCEiXIsUmzH9m1yn6f43GbsMy5kfv/T08qHlASS0tkttFemXTpruXNeGpzBbKgIB1u2EBDZRfNquIW2vTFS6A08YgoF10EKBK2xPDbeUTn6N90dOKeLND8cfkCObwkK+aYtkkfOiN/X8zuXU9BQRNlob5iLpdak1j3thuAM9SZt5xb3dCorojtual/Uy8Q9bUi3FArbTvInzK3k6DNFTy1kbJU7Q6ycWXt+GqYlBny9gEodhE+JLoWpxDp3z4uoiQw8yBPi2Vzbze7JSqXNaxBLExxpq8kn/KLLH3qulBae0WLVKfkfsCOeybEL9CUqnzkizDAYkSGcvQJAhfxwlvUfkas3hE07F7RVi8yW/ATjUMwSIhzdqVp4iR0uSSHHWw5+fm8Bogg/1eSusDLWjv8+1eAv6zvfsPFTQvJkJ3/DodHwfvEk18xz+9+FC6mtblQRmaBZkAI2pXMudkY2wmtVR/uhOI+f456HDrCaEFnnwXdva6pz7WGXvM6O6g90sbwSuNB3H/ElItljVlDU21WEF2wXQ==
  template:
    metadata:
      name: prowlarr-secrets
      namespace: prowlarr
    type: Opaque
