---
apiVersion: v1
kind: Secret
metadata:
  name: lldap-secrets
  namespace: lldap
type: Opaque
stringData:
  # Default: changeme
  LLDAP_LDAP_USER_PASS: "changeme"
  # JWT secret for web UI sessions (generate with: openssl rand -base64 32)
  LLDAP_JWT_SECRET: "changeme_jwt_secret_please_change_this_to_random_value"
