---
# ============================================
# Media Storage - Shared NFS PVCs
# ============================================
# This creates a shared PVC for media storage across all media apps.
# The PVC uses the NFS storage class to connect to the NAS.
#
# NOTE: NFS is currently not working. When NFS is ready:
# 1. Ensure the rook-nfs provisioner is running
# 2. Update the NFS server IP in infrastructure/rook-nfs/deployment.yaml
# 3. Apply this manifest
# ============================================

# Shared media storage - Movies, TV Shows, Downloads
# This will be mounted by Sonarr, Radarr, Jellyfin, SABnzbd, qBittorrent
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: media-storage
spec:
  accessModes:
    - ReadWriteMany  # Allow multiple pods to mount
  storageClassName: nfs
  resources:
    requests:
      storage: 1Ti  # 1TB for media storage
---
# Downloads directory - temporary storage for download clients
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: media-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 200Gi
