---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: alloy
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      initContainers:
        - name: download-geoip
          image: curlimages/curl:8.11.0
          command:
            - sh
            - -c
            - |
              set -e
              echo "Downloading GeoLite2-City database..."
              curl -L -o /geoip/GeoLite2-City.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${MAXMIND_LICENSE_KEY}&suffix=tar.gz"
              tar -xzf /geoip/GeoLite2-City.tar.gz -C /geoip
              find /geoip -name "GeoLite2-City.mmdb" -exec cp {} /geoip/GeoLite2-City.mmdb \;
              rm -rf /geoip/GeoLite2-City_* /geoip/GeoLite2-City.tar.gz
              echo "GeoIP database downloaded successfully:"
              ls -la /geoip/*.mmdb
          env:
            - name: MAXMIND_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: maxmind-license
                  key: license_key
          volumeMounts:
            - name: geoip
              mountPath: /geoip
      containers:
        - name: alloy
          image: grafana/alloy:v1.12.2
          args:
            - run
            - /etc/alloy/config.alloy
            - --server.http.listen-addr=0.0.0.0:12345
            - --storage.path=/var/lib/alloy/data
          ports:
            - containerPort: 12345
              name: http-metrics
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: data
              mountPath: /var/lib/alloy
            - name: geoip
              mountPath: /etc/alloy/geoip
              readOnly: true
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            privileged: true
            runAsUser: 0
      volumes:
        - name: config
          configMap:
            name: alloy-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: data
          hostPath:
            path: /var/lib/alloy
        - name: geoip
          emptyDir: {}
      tolerations:
        - effect: NoSchedule
          operator: Exists
