---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bazarr-cert
  namespace: bazarr
spec:
  secretName: bazarr-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - bazarr.lab.jackhumes.com
