---
# Consumed by the bundled bitnami postgresql subchart (postgresql.auth.existingSecret).
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: terrakube-postgresql-credentials
  namespace: terrakube
spec:
  encryptedData:
    postgres-password: AgArVs3v5jVb08zgykjizv/QrgbGkV6nzOp9fLzbm4wRIXLSUACCu425dP4V8BI4oAYC58j5ibT/bddCop+y0VyN9VPD0HDc7KQk5PjpnePs/QZOnIspUoYGJ3iO+3iy6M5vxm/Lr8bBTCwWZeoXX9Z2UWqpA1O6d04c9qF+9MQ7DOQrNtkx6qkQofQcSSTS41h0PrC0WFy8nf+psNy5VI+Lnk0UQtoKdeTwvEGHD8I//EANPh84qtflZ7H1Z31L5YxxiIO8dOofqWINN9YT0vjjQbrta+/gvrH4OBb7nnThH/4qMESMug+azBirjXj2HZwxmHkwYpUG8mQym+sh6JYL8jZA3vzTi0IaD5ganQd2Y1oi1TK/GEEcJ7ZiNHPG6TiHjfjagsTOomfmV1/SNLWwOdJyjIp0+YW9j0LEB3puQq3kkZF+GAo5+KI336PRUu9PXilNocdqFePuDp78n72xVoTjiZyA4JUiQY1kRTnhOy7EgBplDB8sGKZdtqFd6oIlj5+KLcER8S60zLMO9MDKRujo11PEDIRHV4hUVQoPyCFXMY2Cf9xLcb7eimP6oq6vbeP7k6+75MdtXH/ekG8Rrgz1YFSkLFkEsK0pZWwTUsVc9+jJrNGkhkOIqIZropPdNz1gHftbKpjq4iZD42YceK9ZeNchsfToUKWnJaDyB+5e7SOFmrWmAaPiIh5PhGXuqE40MDdf2h4tWMIU8yGzv6X3nnDI9zuaIQ5ck8Cuc62v/fx4r7YGMDG1ytGDB+g=
    password: AgDXxLByaEGNNXwWSRXcFuOj7qWWfnZYtUSOJ03xaHj9bEsgyx/6vZeD5PwwR+wADSaskxeDln6b/awz+/DMUO9IVM7ZyM6Wa9PnotnIBs2jj1IVPkoELBQpZ2tpwPA2NCpZjQbGQMog+n8Pzj7FNWxOgB4dSbZWHUXglgfgpJQdo+lguYz7B40PTtp76avkk3hy5i81ko/2mRX/Ao2l02NivgvhUQx3fxP34jjtYOcvJj/kqyRbVm8qjxKsgaLzUCWBCcPeiuvXgJXqTyz4QAVvMEXCKE84A1YpnwthJn+GSTpDhBRftozGGFMLw6uZgTWvsMcl8rT1bVTC6InNslofjqIRL2PJZt4Io4grCcAx0YiDAXNMOI17x5OgYF1h6jgCqkKYlPmtEkzw5aCJdP0Er8V/UgpsBZE0+rpXAEx5RfrOT2mpPPLOx+jw9lmGg4XEtjJsQ+Fsllm5W8iYty7QbrF8GWNzcpJnzFYh22exeh0NYWsZljmUb4rbIJp425hdA9/QTpt9wQFuMCHpH0ZthJGLzbGBqi4coPw1R96UTCeEfp5Cm8c3YJze0HgnAq5exMto6XzI5UaQcfI7PD5gH+AkngZeZ+u2azbRErh+y5WWuLklQKmKNOgfBllpsXqYKR9q9xD1ryPPXue5cNa3X7AeYfXinVWxSIXId0EfJA+mvY2XWPD/oLOVNgO/m5aJp8LD1M7/4luS9gRHkbJb7Yuy4aqNhK25toRHsTtfVn3VcTSP/5OhQ/80VF2jxJQ=
  template:
    metadata:
      name: terrakube-postgresql-credentials
      namespace: terrakube
    type: Opaque
