---
# Consumed by the bundled valkey-io subchart (valkey.auth.usersExistingSecret); key name = username.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: terrakube-valkey-users
  namespace: terrakube
spec:
  encryptedData:
    default: AgAMHSoKANwFVwfaUOXUpspGH38C7lpfRSqR5oDRxb6WuY4jR60x1ZSvBsiFQ8uQaz2jBua2SPWpZMNJFYsrSDp2dYw8bTWs79QVShEerwrfG24VfZwMj/ozJswWi0CFKy9bgYIQIWHb6mnB0Js5HVglZPtRGWDlXQLSijGl+7Wwfd5WjE2M4l3cnmU4MprwdDeEaoWckQv81qCeUxdxZEyQYN77Mef9rtwk+V949y6CaxWAoor2lLqDADUSyn2NNinTy41C963fBkn8aIAJhrjYmhJXr3bor56eXi62+N9hbbBaCc10vqioe9Rv0Z3GQcv3GL/RZDd1ra4Tbw+yiYDO4VFOe30svsXKjWT2p6WpvGGa93ZSK6aUFvfxC4O9hPgIv1gW8UPCpFd2lCuBWCLHriwXG2kSnUaYbVDdFw2EtcYki3LGEAqVN2Gv2865x6g9UTQnVHZeLWLFvxmk0OJPeFto+3e6qQDFAeMyalYI0MfqBBckKh4MPbYWJiLFkCICNLIvrw1+YBp+OXhOzoLbDPEG7d3X2p19Hfx79RmJA1XFF6uf09DEZKwi9UDRfBEphrl1fUYtMbZkmyveqs5kzw8jJXZv5BwVb62uwjGzheiYF9tw7SP+sNwiGqanl2ffO+zZfMkGx9PkYsm+RxXE1Nzit9nnFxMF4F06TxQSpYcIsmDGz+4ASAuNcEHnxJf5u+leHbmh+323MPzkminTm1YdpYTID7XLG/PP+32kwnjO1fUKgdAjQuKkkmwvQu8=
  template:
    metadata:
      name: terrakube-valkey-users
      namespace: terrakube
    type: Opaque
