---
# Consumed by the bundled bitnami postgresql subchart (postgresql.auth.existingSecret).
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: terrakube-postgresql-credentials
  namespace: terrakube
spec:
  encryptedData:
    postgres-password: AgAyUAgVrcxfVFk1GT7Sr4o5n1v+oIyQIKWDAYWsFQ0zpX68uaCwQMJIhW90i5t97UZP6F1HH6+E6hY3EUcG7BQ6DJt5qGoTIgtsSVZd44GaVcmmdCmCHc0eU3KuipOvjVTaJiMOkX3ROLcgmz8M3weVV5cjcqY70e8I3PgfOlgzKXPgkyBQJeyXFiCi+cN/Iy2EMM1VCHdAzloycGaRArKFreOxco5iK/jDkxa31snPpdbQsbcFDTsMsY8k1ArTj8zwi+9O86Sh96wmE8NYkFr60HCe1xoQhGkhWGDoP6pvT+3JWibTZrCO3AErpU/JoT889prx3CnXi8HPmTgZL3Mdhn63hsHAJ/AR8uPkUcuFvi+Fi8enBsVsPh6qiEpYsI5l/awOoPBtaVSJU3JWDVnbFbaKHO2rqXsRcPf+EnzQoubOEyrXJjjaIhcJ7aP+HQ/62YgcEZthsDJfACbn0FStOmqi+Ey3zCL4wPVBDPkd9kqxOu17ldMdGIq7TDNVLxI5UijzrpT34SuBtZFa+JFS5xAuSm2yTn+R7Rgecx5fqbKyvNYorihlbiInVkzM6UJ5D9Po4xAjfqvpQsJPVJJ/DAyKLEDXMjZKai8hfQUK3nkIAJIop5kXB/g5ZVMe2/8gr09CqhX3RTulJMoN0L7IwDrFw1KZOzJsqGW8jIu+U9RuzzEHQCrze1RWRrb34kUy/s58UU1v1QJLOqfgGrOB3C5GQk1xbPAoLF6LTv
    password: AgB2874Ucz03zkTwFfEdQRG66dYh3+jaHpiUtEDqdiwSiktS+m+8fe3Yf+dNGDa/zRHKrIaiclS0MHIEYCVcaQOic/oA1C8oKxD1T7S2/fVGDJthSEE4IsCa0l6tKG+joCsm0K6xotmJTk4C93HjvVg3liio1CPJgNUIGaIy70koqU5Zk5pho1uQWiFx7YYRjULIa88Bct0zAmJg++5L1Xfs3A/mAVctW8B6ZywTZkabYXWj5ekFTmyxLIue+NUmLQjrI+n2c766YDwQfwFvwudm9+P3Yel5TNfJptGFEwNBNrO59oRMmKFMboB6q8KTjHdHJ4upQHEGSmRdorS59EwPbTJxxyXgSh5ytvUbZ6689rNeFwx0YVN0Ukhl13i/RoIHJ7GIz/w+8rJEnE8ScwaHKYVNWN66IA2pYi5kb4z1mZT0oieNMfUMe+VbRK6R4dGudsg8dFLxv/Y+g/tIlDzyD8FA0gYFTdHc1eSXNNxVSkc5TdoSKsgtHsY1gG2Zyj9zNC8U/mneh07Djz4BmHuS3DvGJMbbrDKHuR1RiRd4qNQE7kawFbTtvT+S+WCXR+OVLMwMC29fcaXUOnLJ00+H/MKRmHwe9VwGRhmM5ZG6wYLbnLr+o89Z4IMuJ6fJOoYGHret7xA6+YA4SPVMKLbEWc/EREG7V+36eCzsMQe8mAJztF3Cvu9cgrjzG+m0YIOOaElh7IUgSBPXkEp/u+qAiuXl37qNAkiRpVnptTiLIvJ3ugH
  template:
    metadata:
      name: terrakube-postgresql-credentials
      namespace: terrakube
    type: Opaque
