---
# Consumed by the bundled bitnami minio subchart (minio.auth.existingSecret).
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: terrakube-minio-credentials
  namespace: terrakube
spec:
  encryptedData:
    root-user: AgAtzjY+dWAhN6r9CNe1azHAcVP6uixvdHEOzCLDyCYOgchdqhHb/ZlM67HNu7ad1isXb2Y7BL5ngagftjffDgRRZd4OzoA5gQ1mXt+GMid+gZ9yVa7fLBwDiF/H/HwVstiVoiAYIGmVHz8SHZX9kwUxEZufvN6pN8ZhsZHY/Qh7r40xvbsgnYgcv1qGOmGmP8OrICczhxZnif2Jdod4l+5mfHfCQVIUuqF/Wk1Vv4Y0C8beqjj0XQ/+xhdVPcaejU3TiAT4mkFg+mqTwfF6wOOmTPsKaQzrULs4+tiAEHY4TadXkOPc7/TwjGGuYIsVRQ1M179nhUnod7jDqElUIzzLZRC2t/XYWNu9NEhmEN0HX3YoFtNYrYs5TmZdp08CmSJ6MpMn7x5Fqlv1QlcyRK8fjrQPHREngXe39u3qbmrHE7kUEIz/9REvPr2RTDySPCQUIZ8QyiEJd5ClrCHRs+zzAhPvHbjC7UC1NNyNWOKOz536dUaRX4I5msnUf2chxgdFBT+cyymp51JB8VUinWhmTlmeZj0erDSsRbSdQ9GOWQLBjywUpGZ1Vjx5KgedtQkikW30RGd/sEnA/QJUYnP6zQPa6iKZsNU9fM8hFoJAGBE9zFMCrDgr9hdBz5NyfYICzp5Xo8LSw+HOzVjN7qFy3stw6qWEg+D5I8YHnMKQNOdc5eRMUeOmfpgaNGh5nB1banKYWQ/1nA+0Bcz+oyXzSWg4zcQ=
    root-password: AgBI8GiBx3fnXTIIenOX8yMoNO0XPmT/4SIjtQyS2O5d8eC7HaoX0pzonRU7zXXCwTvaaiO2sMjjIgQ+wVgYivlxEk2pyvIqyt3Gu9IQbsJM1gIYPvLpXlrY0hi9qy+pGs4ay1YG9s+Rjmib8jqqtt37/x43oI4AdSV1fI/01676gPS6J0Bk++F6kLivvf+aiCaPXCmorGhsUuABVb36zu1xJEczH9coouMJNurAqhuPLPPK/mcHSg651ayMdJHs2GKlWySIYnuVk2jXA5h4jLmgABO2pJ5kayvlSucMMBPGMtA1svfULcZMkscv/yo1CaBcyu+PlRz/PlMOUPHPhJItV6MwzXU2Tyuec9zvak9GygW8H1gyRZy2EMkaKATJElDqGYv7CZJzhAaJN/jFtrmbblGyDnI4zB+DDMYy73G11SNckHvNEiN+JufBOe4vKSX1gxgeFfd1KJuc6ndJLWh7b76lUL4FWoQUevgNfHn22e2JZw+zhfMfc6KVAgsAfpNZLvX9Cc5UO6Sc2WU6nu/6qwyCPcZQdWNrUkXH6RsIxBs0lMMNigfhtLmcHPAploG6MG/qPyHeVNl+mgjiqKAtCZBAGllYx3qK2ZfS4x10D6KkBJCIJ7MI6K9j84lo2Fp/OiD8dMjoDbAse3kSU5qUZK637z3o/03NdcETpRTgJhO6+JiYkeAhnsw0X8OB5Mn0ThO6cnGPlRjNtCCKpWFfo0sazMmp4eAf0aA7kSTPgk
  template:
    metadata:
      name: terrakube-minio-credentials
      namespace: terrakube
    type: Opaque
