---
# Consumed by the bundled bitnami minio subchart (minio.auth.existingSecret).
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: terrakube-minio-credentials
  namespace: terrakube
spec:
  encryptedData:
    root-user: AgBROmAHIPZ3hOcqQ+No+ywZdFpE70ntpsBdYl+96PTUoggEdLur6/7ta2VIaZXuHcFomQHeiZa54hOL72NGNCUK76qNgO20YlirHE7/ZTmDpJ4X2ObvBz5/T4UPPRsRo3xlPgFcCvVx5BuZ+1iYcaN+fvyLKh2hpcEIIBPATB285rAt9DESSejxxV64vZwxwkht8tKdgZFRiDzA1toT3qSBMA9q6lL8skPG1ivUEgKkaAnYO+RG3BRcPcngqPYsJUqRjhailk7B2X10/Y/9ETCQTSfmsYvqIKdMu+b+V6tj0q/EMEeWbOc+Oion+XBFd/Bv2po10q451RokTJLwad1sPIrFCNh/XGYxaVRwvVleQkbduF5GPxfc3WoP3+IEv8sFKOZJzNjI/i7XW/ePtWtzelRL6JO1FEvYW0xXryHxwm7txx3bWcnWgnAtUCAOjYatITsBcC8j1ds6EzAfPqQpf1TP0cwIEWFPXuz292bbaIs1+m57r3kD4EUEcbMLULaVf73rfyS0v0eVD/giSV/lO+VOt6XLFU2FiONh6miwnXBuqaVkoicu+m+vzXiAxPkFYPi3/5b3EiJSqvsuIw2bwJQHCXADW4cX3KiHAswBWuqvbd5AP+ERCaU0ac6zazXC5wqT+fAFlD7ZQC/tS0BIjcUMxbTKs14BnBKxrWh5+r1s27AkHIvJOCsYxTVwFzn2vWoJgfSzoD3iNQoMGqWbCqCxeJM=
    root-password: AgDP5v7fDO44YK12x0POTM3XmzXnmf8brstP20g0HrU/1NQ08mbjwNPtMe14jt2+oexwKhp8AtHCf2BSKAoTI9OpK7Et99BQ1BOzNCSyas7rhuptf/7RMS3Uu7UaabU/6U0o5jEsxSEQGjvhR5O+3eM76X6lndWQNplVS+uyT3IBd+Mn/BEDARmAOtYoviE1T5k6M6Hx3mmpKk/40Uw05x2vRLvr+6nSBYah3pJyBWHw82+hxAX0OuPNZUktwl3if9ufnkjpEJQo3Qv75qBkRIIYwDGbUDRYANvnUTgaKsX6P6v2eLL7VyLZ5crUVvymv31bJndP4QIvlG9EGixBYLa1r1IwXrYI3x0ib2mxWT3mohZBQwO7HgF7Tc8bBq8rxH0nfKU6u47Vjuvf+T18CLa9vlk8F2zA6GFmiSn5pMumvcO31TRacBITXcsbSaw/VroJHIvoCH/l3/IFyMluQfUd0aavOVGtLY5A47v9VOppX5HXCJhPu84V7j1NX03cm7w2eb2+coVL8kJ92DnWTr1HNMLVIrpYphtLEiJP3B7I+ad1Z8UVVHyQZyLOzq3yd+E0zd0yEZQHsRN8YvB/h86FzkbHLG32zTCEuSwSXFLjqlVMGOrO8YTVzAkWULwszz9vglh8wLrSOIXmICfiEDK9huf9DTJd2GNRzPXnAn3d0lZAiSddHrLVH2uZ2bJ09HjAxo/57ozQ46X4w1DWVosANiCVInJWW6YR8mpO+Gf5JTY02C6GpTM465kO8V3SWIQ=
  template:
    metadata:
      name: terrakube-minio-credentials
      namespace: terrakube
    type: Opaque
