---
# Consumed by the bundled valkey-io/valkey-helm subchart (valkey.auth.usersExistingSecret).
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: terrakube-valkey-users
  namespace: terrakube
spec:
  encryptedData:
    default: AgCn8I16X15jbRTUYrhKm6f4hzAfv3n1C+q7h+1MMIMHDXiH4mBGbsOjoB6B/7k103Sda8ysJpcySLl7XIVxCDoCmItrcN28UqgxYJynERQ7K1/M1vJcbG2EMwOKVkpfZrY7Rj0QRBdsemMEC2uQ3aqODz01cJehFWd7I+XzmYqSzsY111Z2mITeT+C/fCs5RQOXE9/ywRgYpipFLlZ8mAUbRxAHc/Xx/zF/HtwQxgJab8PsOiearTT4wJyzylBb9gmXNd1AWQKS1J65ieRcRTbAV5PJrAZuXHVhnDbOrOYy3RdWIk4e29y9iu4x9p3A3yDYD7u/EXBMi2Hcn+NJrX+OGxrS/E7L1LQgFchG7jY/N4L6l1B83RhLMUnWgdvtJI+mglQtkSR+TaerneGRddfifAbvBJJKDtysUs8/J5EHR1VTzbzEv+Hvmk3f1hsY8BY54jnTe+EFsHCAg9XK3ReynbPomLvHbHGWtecAXZGIjfats5GDorTYjjtEcPLYrbbHhPhOPgrImjArHjeJo3wRkOHxYAaLsN82YgxB0UcXYZ65WwHALNrgM/URr9z8p1ZbUmSL46or5Ah23D2CyxGMM9uNNHdJbmhyPcbuHpLVIQg24FwGz62rQLcaeFAbZrm4HpEjqTSdYOo2z5A+RGM6W32fxOfoU7hubvt9elPQYd/efu4UKW42Vp/yc2Kv1LjAeHLMOtd0MPhTZnIexK9iAnzuhZTwcjTDIO5JBEAD2MsOVBTe
  template:
    metadata:
      name: terrakube-valkey-users
      namespace: terrakube
    type: Opaque
