---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-cert
  namespace: qbittorrent
spec:
  secretName: qbittorrent-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - qbittorrent.lab.jackhumes.com
