---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gotty-cert
  namespace: ttyd
spec:
  secretName: gotty-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - k9s.lab.jackhumes.com
