---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotty
  namespace: gotty
  labels:
    app: gotty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotty
  template:
    metadata:
      labels:
        app: gotty
    spec:
      serviceAccountName: gotty
      containers:
        - name: ttyd-k9s
          image: dylanbstorey/ttyd-k9s:v0.0.2
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: HOME
              value: /home/gotty
          command:
            - ttyd
          args:
            - -p
            - "8080"
            - k9s
            - --readonly
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
