---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qui-secrets
  namespace: qui
spec:
  encryptedData:
    # Pocket ID OIDC client secret for Qui
    OIDC_CLIENT_SECRET: AgBQOLBoyHhFUmgeOFpQ/bI351120uTkJFmCPgXFAAoFhNA2XJQX8zZK6pkDlki7VIJk2tiavTh6aWgPTbp9tCjxNdOp0gAJGdESO31tr/I6OyzdUL9RghLD7C/ndCh3KsZ2QPF+cUeGFvZK2mdfPBPbUiAAgdzUKWbF1v6xwLWZRSSGgWJWVXl88Bs0cvjivFGUZUqYvzNeOuLeYYSWIS5w92hm5yr4gwsbksikQniQovC6iWuPx5VNNCICuVPF2oMF4G1ucSNPA09Aorad9pYLLqYiOiSe3xkHmV+hbqF0Ro9mEMwUyEcH3gB4WmrFNpNVRLnI2BFp5EIwys7O5gA08geZQ0v/6yjPg48KRRKfaYJxdOFH1F31qxCUZ8/v2KuPaJF4A0o7fSI0RjHwitfvXcdwNsp0fy55VQMAELx8WztnM4j5B9G7hdfh7b3WJZHsp2NvWCk+gpINLFuN3v4mQIQI0VamqxIv9IIyQYcQJO/RoHK/JRcX9VDkIYxlxQLHCukwlGyBrqByd9ErYZWrcmzRAeCIi0wc/5nUI+TwaVcsjWdE47WbzphPehGFzKLvrXBWR7eACj8tfzGUkLLC3B4kPMchX6+63c0SSCDmNrQ/6/ti4s13WKUrZs2/BV/KU1USC/Ep5vryNhw4FSsyS4P8ojEKAV3kyZvzo8RB5peyb0N+xBvZzwcQur7Lg4AcSdKr/FyMBlRdXs7eI6dTwrjrS6+l0I/VMNGjDfcbYFD/TpYcsWYDQI5Ysg==
  template:
    metadata:
      name: qui-secrets
      namespace: qui
    type: Opaque
