---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qui-secrets
  namespace: qui
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgCoH3MmzUftIr3HjUNQ3o5pjq9Sfw6k3Edb4OBjAvCcSyOmgyUrjuhXqTlsurYxN5dQgRWRd7F0vv7XU7PNaeQPmEHJD06e9LGRHQ7Q6Mxb9w2grwRaY0N/nP/TcLCGY1M/wUxhQCreQHPnZjg/p2WnEqsMIoLappixbPtnCYBMVReHzuqouqOmD+Y0Vug4W1NEKxEyocnQKjk/FKmlX9I0tYtAPWrjicOSz57neApN2xlVrcIK0Y1cFRgbRqBX+G6KnBRCTXkU6lAXl1aTWxc1ZLboA+QoNc2sjlxcCxcc+SxoXtsdtS0wKL7SmdeVq2wcch73cRAK7pGIz/e+LKGgvdUUTdTRAt/JUcKxXMI+KKflB+ERuR5iE597mUkzjMXLvdxSch7b631GF1uE4Eh2GoA0kHlgANUOPX7Udh4Uvk3yn2EwGVwl/7wDVCFQBry9hjXsPsmmORbbbMjSA5yUFTs0qbkh2JOhssH6VkKbhhkIJRKdCv0pXjSmOt/lZaJ8mp0R7hc0QqdlU+Jy87yc/YNWh59RpTDotJaumcOvLvFMv7K6X6/OV5RncdM+w9fOtrFjuLJ+It5l7/c3SiigAU2YIcwDfvAXW9NdaQTm9ygH1guY1vGek4PnYDxjCZUa+LK7f6b+8WoZ0AYNkas+geHoMPoVBLpIprBIRApF3rZVA9Q4518Zn9ctZG6Q3zIcI8oc45s8rpyEBMYtIh/VrXIz9p+Dt3OavwdwB87Duw==
  template:
    metadata:
      name: qui-secrets
      namespace: qui
    type: Opaque
