apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        log . {
            class error
        }
        prometheus :9153

        # Kubernetes service discovery for cluster.local domains
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }

        # Forward all external DNS queries to PiHole
        # PiHole handles:
        # - Wildcard DNS for *.lab.jackhumes.com -> 10.0.0.200
        # - Ad-blocking
        # - External DNS resolution (1.1.1.1, 1.0.0.1)
        forward . 10.0.0.201 {
           max_concurrent 1000
        }

        cache 30 {
           disable success cluster.local
           disable denial cluster.local
        }
        loop
        reload
        loadbalance
    }
