---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-exit-node-manager-web
  namespace: tailscale-exit-node-manager
  labels:
    app: tailscale-exit-node-manager-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-exit-node-manager-web
  template:
    metadata:
      labels:
        app: tailscale-exit-node-manager-web
    spec:
      imagePullSecrets:
        - name: tailscale-exit-node-manager-ghcr-pull
      containers:
        - name: web
          image: ghcr.io/member87/tailscale-exit-node-manager-web:0c494a19087e52255172562f3a1655aa80a4f18d
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          env:
            - name: INTERNAL_API_URL
              value: "http://tailscale-exit-node-manager-api.tailscale-exit-node-manager.svc.cluster.local:8080"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
