---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - hostnetwork-guard.yaml
  - pvc.yaml
  - configmap.yaml
  - sealedsecret.yaml
  - sealedsecret-ghcr-pull.yaml
  - deployment-api.yaml
  - deployment-web.yaml
  - service.yaml
  - middleware.yaml
  - ingressroute.yaml
