---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-exit-node-manager-data
  namespace: tailscale-exit-node-manager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
