---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-exit-node-manager-ghcr-pull
  namespace: tailscale-exit-node-manager
spec:
  encryptedData:
    .dockerconfigjson: AgCFBWOjzKXe6Y+ynYLm63uFTRLbwOrY/u9xDXbXGktchwDOZUK2TmC4MYZnmTn3Upejgi0HPjvavKbYCvLJMmWCC3pKz44hJ5W5WjsNRFA6KibLVODNCotgf/PeVcAC+m6G7KgWqDXqns8W4WV8dypOUNCU2bCphlI2dhObffqiMJUNjUJnxn+94NcYmdxYK7GQYkVKJu6fd3dbgYJnQ76ii6d61yhlB4z8FByYasIwb2HPJTTmZP6RoKf+b9j/69yJjvKreyotOMzmEFUAUJbCAZsxk41n9VWItwleFzdmBVaJQpocy9uocJeSLzsVD15w7poF9eo4NRuUpfiZNGzBTr2dOdlg2WIt0lJzOFQbTUIbrMIJikeeYY+Io5EO1Z1WLvP6feScWs6tXMeDrdrshkTbML2tZevXnDtQoTLP/RrOWs4//DXur3flO62axmwXnP/m+FzZdFVYNPw+oVslpyQ7PuZuYhapT5izbZoJrrQsAI75SFLoxhlV/SXYH+P61197Ib/iTZKgVhAugu9PtEFXffX9ywcBjmHwmXM53qUHDOKhYgyyAP64wOlZZJ8l6ZsK9PhoOhdNRC6Ia2I9Aqf9joujmEVMgDrHy+Te93I3SIDM9+ho/uiN5vx1fkdIylIdzv9eoDQ0TZIzgTMD6yOut22g0AzfghgB8lss8UHi+78+zLc9GreOONGiabLrRTWdVnW91UQ6pb4a/8Q5WZeaeoD/fldRU4pgtyDcyQMegflxZOMZiUoQkDsh0c+IrKoNUrbCkZ7AiOkzfPIVxWgPMpQB+CGK4kwc6W5Ae4LF2MlCnmqTnaQm/3q6btV+Hy9bWPHcJNyP8jwUrl8ccBD4oY5QWJgOu/pf1+rvZfs33Wml0HJrMIQM0gAg19gIv/DuA5QsZ7E9EgP8EMqOonECFYFWy71AW0ninNiU28k=
  template:
    metadata:
      name: tailscale-exit-node-manager-ghcr-pull
      namespace: tailscale-exit-node-manager
    type: kubernetes.io/dockerconfigjson
