apiVersion: v2
name: pihole
type: application
version: 0.1.0
description: Pi-hole with local home-ops manifests.
dependencies:
  - name: pihole
    version: 2.35.0
    repository: https://mojo2600.github.io/pihole-kubernetes/
