---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyseerr-tls
  namespace: jellyseerr
spec:
  secretName: jellyseerr-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - jellyseerr.lab.jackhumes.com
