---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secrets
  namespace: postgresql
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCX8F7Z9nLqo46ccIqyJhm1w6UjHBHu9WfZH8AwcnoPfbINo1TiEA0Imdw9ejU21Njfh1P9v3Ec94q9tTybXMTUu5nOlc8sJiaQh6fAvAMUFmhP5VuMsWVYErbh1IJmgYXFOHhZxzBRCQXyInpBmV1GX2TTeenV8qG7h+I9vNsTwYDDBvtTQOb6olVWuor+1TzcBWkZy8BLrvMrCgdcvzu5isMzI6uwHqg0agqipZBzz7QiZVP7j5Y2RxPQvkBTSMJiCebXOce9pzHSqIq4xVIs1T5OJnahevfA4WReHGLhakys0cxjZUhB2/vlUeFPHbZbUg5E3tQXAwrzi+rcNsiRkG0XvcihoCBTeEMhDztaSXp9QbQDzDbqnNk2gHJUrIXPvng2RBoABPvnotKHtNMrpYLOkR2901eRS0k/rDlRUqgMystx9nEo7b16N0vgjULmCB/WdjajBUDpo5WG5N7eDYMVzlNn+kA/TLZ9SZ1WJDevGL11bMPdrB1/waQKfAvVl1znzyUqR6G974niXfh50SEZOSb+AcmTnV6JbNaUowsXr0Vb2OhJwTWSZXEut6v6Cr//xnUVHDluQPbMqta0fMs3Ic4Bk/Cd9Tq0iJytF7ob+SflBd+hyC79AtDYvYuMED9y5ElFXj/fG25kI3tLPB68fqva2WyX2VgRoj+apIXQN7BABpCB1P2s3TUsiMw6R1cgfEdPjIpp3i0cfUVIyJvcYUR3CFLihr4vYuF8FA==
  template:
    metadata:
      name: postgresql-secrets
      namespace: postgresql
    type: Opaque
