---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secrets
  namespace: postgresql
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgDQgQAo12ySMMHwgIstpWX5RpxbQy1NqZ9Ft/O4aITzZ+CCK9dyWWawmyIodcvYjBt6L2phpJIkgftIK6JjsPotFrMqVLbf58e4C+Fd77Zp60LEnf4GhHaP/Sh505sEZ46FO6thCXeWsdO/4mTqNXtnF9UEI0doxxUAL74D9D5S6jf5ipedhERiaR8jdsertvgU5srsxvjszoa/gubCOMpeRA36nSq4mNTuwsBpPTmoHr8eoyhSo83GE5/wKft3UjR7SkibUWNenvVpkH7O3ZsNU0Y9vfm0YsBMGbXRIOd2vYA528lmPWIqF6RQXh2rtb01ZK9XfJL7hlgvSmnv8O/sqFAenIjneNYbk7coa6tCMdjLgUVaaOcHwpFQh2R5+n/pw3QVI514IWpUuQwC7GJpxBmfWfNJvHoG7HFHNJG1tQvFe5KQZ3BHTR1feYz1U42j65eE++OBjks3CCaOLzWmnbgAZTjtSOgwEVpPq9oLEDeqfK0Hgcxk2DOyOp4f/AJsgJRWwT/qaV066m4bIofGOBx8Kbt+H/rhQFUy8W2VMaT74e3PyXRRYN5Z1Fqqo4QSr81mlCFjASKdfj+lWnaLklEJdzV4O7W4mIB957v6UHWoxsDjto/EhQycQ4vz8yf9CZHqBQkHky/FhaTKiXNodmzMP2rOkzYgVw7xjvKkd54AtSgxWgiHEl+P8sIMpP3wQYGulUySmW18UaSfjbYrvL3Q4OJYnOPhWdSkJRr79sY7
  template:
    metadata:
      name: postgresql-secrets
      namespace: postgresql
    type: Opaque
