---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCZpa7vVIAncm+vLy/n9PEdl5teP9a21oyouzU1bMn1EerwZYSygPzFBa7atPmd+0oO/cW+28nRn0SmRBCNt+5sOnfuCzzwE5Q7bLLXVyt3CbNi585Gm07UATBp1xs2CpOVpK6f/AVWOzovj+Sz0bf4VuYR0y8EyPg/g6AJ5+xm7RUzZwwuQRNbiRaWuuyLzjZpyKFSOJPO+WM0mtQ/20/ImJ0hVpZblA4I9qDB6L3DDFQnrJ4faIuU5BR2PSEbhPpDaDpTat1Xkzyg+fY80uQX9erxstORcT1BoMSKA2FRI8cuoOQoyAREcA9njkVqadbttnPOJ8+TaSfTyNv5PT9LY8NieuSCfwh1yAUlzGpSBuxDT5FceLEa9f+7WVjC0oxNKM+5Mj/s/Vlsru9BRiuTqILisjtlqI/YlthDycrOM9lcOqu7Q1jWpxco17lxHGxpKr4khdlJTfzn6sSn1QZ+1MUV0z4b+m4XxS82D63xQP0c3KhzgG7QWHDEfzN5FZ/iy5AwTj6YgsS+fafJXkhXBM6PcvViDqYoyKKRNPI8hGrZRULK6Epf5t15QAhoVmJwLCz1dwXR8Q2Pni05IaJf9fareSW822KNJwQCKjCtNeSUNXapiIKndGlwLSqRRP/5qeClXM8zTRHTaoSmZADwREIkTXkyGg/PVP1i7xw20G+bdArYtWRDj/fpjiSxiOCoa3wgcVgTh5iB4/9w5KPjHWqWDqq3QIRUHONU2dpjPe38g6BfjStW
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
