---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - otbr-scripts.yaml
  - sealedsecret-thread-dataset.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - certificate.yaml
