---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app: home-assistant
spec:
  type: ClusterIP
  selector:
    app: home-assistant
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP
    - name: otbr-rest
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: matter-ws
      port: 5580
      targetPort: 5580
      protocol: TCP
