---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/weaveworks/charts/weave-gitops
  ref:
    semver: ">=4.0.0"
