---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-secrets
  namespace: gluetun
spec:
  encryptedData:
    GLUETUN_CONTROL_API_KEY: AgBpdgr2JYJTy9xhfReiHE1AqxWA58Rxt+b78TTT77DOwr3vA+5nB0K9inMzciLsaslZdW43OKILa/iL2lJ5OIPsHXwXaf2U3E+ORJghK0yVKeTJVuE+pNHMunC4ZXm+aPczwVUqJD29DMHA0zSQ3PXoXGC6F6+g+RHQ9hgmrb3Og6X49CtptO/vpH0XkNu+OLjBtyA2820Nww4T7feQ6BQbG5GKG4nznmyJxsqAZoNZRjgN5CU/4cEgvqjvVe8pKAMk+Ypr01ynwziCbZTp46zfU6MoKfkcP0X9E4l0yJe+r8VaNSGj8+fzal7GBGUdfI0wuoUJ8xHTHYLfuh4GIYSxDcR2yTcny1eLaIhDYxt75WNmJr/oCdvcLfDIu4IbvdTU5SHtSZBupGuy2Gzij7GHg2Q9zGSRPTVcvWpO3fTGf4blRvUHT7Bc44rRnlKT5lbBdNidth8Xeqy+vyoWts8xxv5ShuF0m+B7cpGbA5BNKCDQHI2Jw7FY1xGtXCIgMs32QTfPLy9r7m7aWwBgJ8mNbEi0diPjE72l7wxb0zKaVQr6qq/2CcGFQ+x1wK8iysASNU+iuEtJJ9oXh8tRuetcKBAgyajjhJIYwYagatosaG5LrNbul7Asf7yKwQrQnALMpC2KZTMQLPB+YIEhU93sviUi91jbxWztsOZGLvB0p1RmSqRoCMyUUw91QVB2diO5judlTTPhKYt1nicpHHJyCB4v0PdplPx2SC1/KAa4v9bVmETxn65+je5gJQ==
    WIREGUARD_PRIVATE_KEY: AgCdd1AcOIbaG+2WaS/L4mXPq0SJXW3w9Ym4YFS7ld23rX3+BzWtxmcZ9Wbvz30P2J7CvM6zk+3ZBpLfODALvuXw7u0mBzN9VkDSgi/EJsiaRnW8/CTfvgu0C3jSttbt9qzltHIJHCjNXo8CkYZ2bOD3pNZgRvvR3O4o4mgirWLca0/SKWvl6rpydWTN90kPXxFkZk5IfYBFscA7RVwRzAbh/ysSOSdQdd/OHT7VCi+xUMDn4xlSYxL2AdmxxlhHOjXSz7k9QYO6XG+w7raGEQJ+jMvgk9n08FIIzNzhbdu600iA5T/M4OA67fzEW4yq8KDvzN3JYKEzs5IyKnfSOuASbbRqLO5oxa+lN1hdc/a20V7RbdWP5Y5JPe/G5bzlfX55MzsJna80aOgcCh0rNnUvcdgWrJpiUUrH3NLTRlvPGeYFVl3XJ3MivXG7KBPOAbgeBHtS7lHMAiEavk0FeNFn4q1qRddxFjVO6DmI5AkY0XnZ319356HI7tO7wimAka4oX/5ppyelQQCnFSxjvUk7DpVdVfCuufdi4OtLrUflbK8Q+0X45gGQRkGXZlpKy9zI7u0GTCsgXbn+nlGiu2/ynlgx4HEJOxcCF2r0qNc0/jTNcc5p5v7tk5YxI/vf4YZ/WMzuWV83dZEehA9XZHe66PQb7XrMJKXWUxNJL3KeQRihvm6EO0UmWN4S8ohU76UaX9KNnNizmxisCb6qTaYA2+7o04W4wppzGaUBgqAc1L//WwAXEW+edVaXIA==
  template:
    metadata:
      name: gluetun-secrets
      namespace: gluetun
    type: Opaque
