---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cdn-data-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-manual
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - proto=tcp
    - hard
    - nointr
  nfs:
    server: 10.0.0.9
    path: /volume1/kubernetes/cdn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdn-data
  namespace: cdn
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-manual
  volumeName: cdn-data-pv
  resources:
    requests:
      storage: 1Ti
