---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdn-data
  namespace: cdn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
