---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-dns-state
  namespace: tailscale-dns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: longhorn
