---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: tailscale-dns
spec:
  encryptedData:
    TS_AUTHKEY: AgC2edLsG4rOSFaxczKrrbykssjITJERjXFzf5/KzVNj5QJgdGYK6JAK9EWPJUdpyASKp8u8tukkHHKTTmKWi0fhwcDWG1nmkD8/TJPfRlhGNgqJuYAW8XGoOxHAjecSvf7v/wpvbn/pAsMychsFb7Q28Y9P/F5eZSRBhRMD2qEInucUHWq1Y/fSR5VNbFI875Sk4UTgxbM6UvpDfugJ4zVWxM5PJ/C5NCZWs6tp14MnrJS6io2HpYAEcJlpaJZ5Qe8Ci0p/6rzuJ9UjmL/bHhv1N6Ksl7UiEJyEkyPwaDs9Yih1Uvohbf2v3N8ztRTMH8+zpIvF0eQlRw8IlsC2wISEH1FOhavxnpxH4rm3uaSNqj2bRS1aPoLaJu1oWLtHq9LOAFxMiwSBgIoSn0uhzZ61qLGLscTphax4LqXTPk+mlgYh7HR7jEhTX49xEKSvw3a3N1ujoV3JEDqrzXxkV6RbWDodS346qLQAQ+qgJl1IE/Nc2yDea+wOoCHkdoj7sT9J7hZzpbBylmLYLGTXjlRwc89lpXBeQ3wFLYyzj18SiXrxso34EE10DxpShZPnhrPtAKHtZV9GQROFXEpFb5JhReh9alz5TpleeQ4Modicv2YcGkwIdSz9LdTvB9UaDrDA2FHKQOSeWvc7p1jG4A9l4l+LFcX+qzkRpzG9AC4jgruSiR1fUFig5jU1h1YmGPopTEExGW7PyuiHQLVQZS7HgDOkxbY3wVJJqYuUgz0imvRhh5fBjczZDEYyD0mjEQhqaChffy+hoYdFOeDQ8APuSKhVPZUXbbyGXiuP1pKQuq1AHArsOb9m
  template:
    metadata:
      name: tailscale-auth
      namespace: tailscale-dns
    type: Opaque
