---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: grafana
spec:
  encryptedData:
    # Grafana admin password. Used only by terraform/grafana to authenticate the
    # Grafana provider over API basic auth; humans sign in through Pocket ID.
    admin_password: AgAPcIn//qcTUqbCLVrSpuCmJpspE7nlrc4JQYK3Bpn6Saa3sh7gfYgk9lsDj5idQBta3LobgUqcgBTyGOxWS+NcNrN8XeN6PGF+XUVSSHkNoybU/KUtN42JQdBpVLn862nKYt9qtp0TW2OzIObk3CCKpXxtTD4qx0HKXRP0HNxP2jw3gJDjZl8nf997BerB9vCAvX+BkMWx6gqN5059VVxJq1VuWMh7n1Z5ggg6V77KLhjB59+fLYNG64P6KHJaJlCybNLww7cW9jOf4sbDG8yaLQgm9AjKwsX2KkKU1kYENEvPEBMtbd0fUTr56hj/6uB8LbPpmPYsmwwX8oxX3YUx2jzQjyBcmkaFRpEh3lc+XaehTDYAU+DTHsJJSFZka6C37yYKaKiMECkMGKdtwmaiMSegJs/h9wI7meW4OriwtXTj1IlLwsCD85PxiEGYHuskG51q0iqKGFAILYSEgnnfXsdv81FvuX+9pqD4WBpIzJqxtuMu5mY7hA6Vbyfad+jswxsC9NWW2ydH55t577pt3vmXbB8f7roHE/eSIg2pqHjx8uU+4c/t/FTYxiMicSkZJJOr1B0ll0FX6TxJJwOL6FfyUhC5COavXGHYNpGe3Cmyt1YAX/Y5kXZcTWdu58XG96qWmLS6n5sueJGyqMP9jOkO7TsIFvK3ZjTq2qoBhpjRQbf5aSctYTsF+KZGxGcQ9nwuC/wvR20Mmvna7sqcsoJzgaz3RNKOJegXFQjN2w==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: grafana
    type: Opaque
