---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-alerting-secrets
  namespace: grafana
spec:
  encryptedData:
    discord_webhook_url: AgCQiA0R09H71L9ypadfoA7EQhNOH8SSB3CUOtR9giJGLiJ9vEaB3R6EspinhMfBq9ffq3Bstag8SaVKD6wuod7TbXUTTCAktJAN2MvWcjX9XNglkq5Q+YBDap16CuNDYgujCcZNZTAPQj7gIUaaxs1MJC83zG3pr2edwxE6CSS7puIYCDL2vAWSe27lhkh77qI2LPYdBenEVI0GICVQg0jLO3rew1Aq7V4D08GzhgySPDEpUZMQ+A0pgehmjXQaR+SDv2t+tq+gdaMFbWu9smLVLlVxQlZBDebGQ2/7JUQ1uQzr+Jhr8MYr0hP5AAYWQtzvtOcL3MqxnON0lhzcePN6g5FSjZP0AZq9b+7TVyknZwuaaZHxDyQArE2ZtfrxFVgWNR4aMToYIC48IKfCZaefhZvdbScfsDXGk8gWjT+lpTDWoJrjvzl5fGBDM5/thgXx16eDJ0qt6nTR8mqQ8BTDcWHb6n9sXExrTD5Zrr4/ueYIz7QrUJatQx/mfRQCb/TrnFFnuwQmcun00Icg7GiW7rhUTnkEcOKsOxu1opQ6nKptRKh9x5uZ6TVn2w8xZSUiXhy6PjWQFv9RZORzWCkHdnodjCeRvEJoxkJDC7hA5978esdsRp0vIwrG05wPhUXNEugHpTf48WJda7sBlvlG5/8NDmr8JkSLsPZM0DZuk3DjSPX2MoskoSudhqgWfbdchIq2SvkwimMnEwdVyvD5dXNUJxGyEQtnM3vWatOKMHnP2jYglHDXlu/Tc3db+Qwp+lPQPKkfYbHO4RJlqxQOtHvYyP9dtKhyyoQYPRCpnKaSsF7XIKZiTgljWjUYThxlf0A0/kq+EMJ7RnqYyqF2XFqprldzGjhW
  template:
    metadata:
      name: grafana-alerting-secrets
      namespace: grafana
    type: Opaque
