---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-alerting-secrets
  namespace: grafana
spec:
  encryptedData:
    discord_webhook_url: AgDTZJtf/cpFB1aNEd6pBD7HtBeZ2aFQm4lIiik27ZKyfJUFOaMFf3lAe6G/XoADAaNheYz5luw/Fv5hFbQm2ey2a3jLgV/Cly2Ujgh3Ws2XDT+ds+e2WsH3zXaIIketXiJ+A7XBVRfWgkZ6aQ5bLf+9uujNjtYE/bCpMaDRqlKi4VNi4n9dbXHFFeJ73CdvAhjaT/EyPjIZsGUcOPCNcos4iaX0DI8Ztu8EL4YPtVf8xiIuGYBhLDdrvWWtupgQzMGh29LWhPzdGRTPmzvY802Zv9TIPNexbYna7xzfDIbXoTCQkLun1qa+bCeKqArSGlDdS+I9GiZJjBYMNI8zKON6mHj1Oa9D+W3XlJ2yTHlGo6JblamvhxyPOSalJd5y/9UdFeMhTllcLeZou1mm9FrnBA2Gu4gCJ5qEMBYxeavSfgD2PFKqlFc3GQHqRwfJml4XdJqsz3pU3gcFG7ANAEBVpbryZ8Ws4prkhyJYrdpNpfVXF7cI4osCoyVp5qqdysRXM5njkk90mzrk1cz/c/Hn4pQqlGK8oXLcMZbWQJY3LG9i3p8ReJlAeA8qgwyluNbpo8jeMCkbfHYyuSrh+cdA/YwvwxeMA43YDqv15J6CdZhrYf/jl5SQ81MwIRzI0hQQmKUtBbJW6vVOtETsP3N4qTwlFIT4/uyTvEt5OUFW8YVFaWXkq+d22BKGIv4aQstpalwZuvJ/2HrRFx80PZ+7wu/+d9RjDSrty+aGFlBGouXNOSoZXQ7Nedc/a3E7K6zbmWNFds2SRSMrpmAIqM/xyw2wM7xkKvEeI3/a0xUGSzmYc0XtOC5jBySPamhfqrvP00wnfahP4fat2v9Bg+oA1L6Z6fJ
  template:
    metadata:
      name: grafana-alerting-secrets
      namespace: grafana
    type: Opaque
