---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickhouse-secret
  namespace: clickhouse
spec:
  encryptedData:
    password: AgDSOBqiLKxdknBRI2Yt5rVy/VHuRDncPBzEvqvIahWtPFJEL4EAsqX1MtmqbrGW7w0VH/T26r9NAmLlUUtxHFQ62/8UK9GCwcRy7yQeiTNIwVI6oVmHgfdTgPfsTJ4RALxoQ+SS7E9PsLEWQ9n5TAP4sY/pfAeenMa+Eoe+w7XEB0qADiDMKvQ8qAWDNhGmaQtvbJaFmr58qSQlbVdeZKbdjdP/MHDOzE//CgbkGd0qe6hzd69RRTyCTmPDndXUNYqmAj2fLVOejeQuG4WTlpEvFhi3GViufI/GnKUyJYWXcW/BewHfHVGSDA8FHkEII004PWnWjb4GmIzvSgNUh/tQfL01T3+96o0J0yo/mk0ERxrVSH9RPnw4vVUrt0VzbNLGdZT06HnOD91WgEMt9LcUdZrilln6CCHPRviqGADrmjaQyGXYzE2VGdDe8QoA7Uq089wWojHqbKsL+ZczagYol7SdqWlojgapKY4pW2CClq0pQYbYKZLSREEbJ/jdcOl9x1Nev7Klyx7UaNoZnyR6kLP4AoB2FtTB3Kn8SQA/RYi1Hsmh8m9z8zH3RSyfub4mk3267C5jbbcHrTIqvYVOaeD6EL40bZcjVp0gUiOTigZgIyqwIwKRfJuFV7hAq9afNnTLkhYcfNQUYD7RRAXyw+5fzN9yqDuQUa9x+d/14oZOxhNA/XIKdyJPMCL485jFPFZgzk3X8pv60DfUSqG03SiQ+On/tOBUU40MfW7Bog==
  template:
    metadata:
      name: clickhouse-secret
      namespace: clickhouse
    type: Opaque
