---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgB1pbLF6/IvRUqa/NHG+f4KQs43ql6rJZ5FBdwc6JkpAQtd1IbNMb16Hs+rartKLWVGxPimzhub+cAlbXHgdLAmXUMpcIAx+NAUk9Ov6KelNGTe1jXqUSXp6ETjodwwaRf/TZcsfcyVf+2MN3vkJaegx5qOlqCa/zYuxHBdZpkCpwMTOnvtEQvkf56ISYTuF9bpnz6ZLSGYZpA9urRCgrc/pfNZu0qc0Be17bLwifFObw2niP3YrutTZ8+YHGNKZl2XuiFBqoep7BqB2tI7CyTl0chU89kOIoxCfvfxcL1Vjw+N5vWNr2LizEEt/J8wNtIPBVgNI1SqoE3ddTLeZ87LhM5NB7l1Z3tuPmJCbjPLuT/O1tBSaoBkCVOB3a27oSLcn791IJ71uM01G/8xyzo0Vi2OQ+fga3UwxnKQ9fZFzYRRGSJGDLYbl5Ro5jd9X4mS2bPgFeBxctvHX+ah3bG5fpNXMQ60cTjTFc1/pQAuWqEI2FvE0ya7ntk8Z2cDW19F9OssbOdKL8FvET3rerAgmb92i0hJO7pjRcuL1pVfWc1+1VMdv34JU5DOZJsmjOU85cpecZai5LFV4gI1gUz/8P1ehQb0wzgDqx16hEBeWiqHK7v4sXa4LrgzfDQtJ36hr9nwIulzqEsaqdtJIwRmnMKBb1VYw7phx4sV2HBFL6bSUG1Z70i4yMKFjf6VfZ5CiLB6qr2/vKU8/w5unLPPrcRDry8VibkX4+wnRmlat9V/WvzRkMgMq6fVOM9lf+TiR7QThDjNETxwXgM/2rwoMCf6P7IuyiCKEbg/V6n8QDmgldWvcatErSJcOWSjyIDG/gGO2d9oQ37zZLLUi4nDSe6PccR6sUnm70Y8nRUCED1Mq+Z8iv/ctYrx4FVxwZZT2EMpa4UbNSCXt2AIYmLOzED/emVA59/pGrEGvXHDG7GGQ+1RkEwD
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflared
