---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  namespace: mqtt
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout

    allow_anonymous false
    password_file /mosquitto/config/passwd

    listener 1883 0.0.0.0
