---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealedsecret-mqtt-auth.yaml
  - sealedsecret-govee2mqtt.yaml
  - configmap-mqtt.yaml
  - deployment-mqtt.yaml
  - service-mqtt.yaml
  - deployment-govee2mqtt.yaml
