---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-tailscale-auth
  namespace: mqtt
spec:
  encryptedData:
    TS_AUTHKEY: AgDH3BzLoIjM2hUMFh3BxKZ8hyh3jhn3GT+hZdkIeUnS/dkizFoTwfabwu1qd1fsQ0BxSRDkqAbisdwN+G1bqYaUrBVVTLYMouNbG7MNYIGds0FsLraYwyWtzHzacK6HzphzE2/eTSGobhWu13aM1wP5riBje/XXsaGc80T4+mqCOMyMDiIp3XykGWIpvK7Sc9QzNl0xLs3sWxY/zhjCuzTWx+h1UGvTDinU0e6NbbMC6ftM9c50e8F3st/t9SS7qFkuk1Mt11nUQrrEGQQ8ZeNVoy9AZLphptqmvgg1ZOiccE/dO2pApny7NCFf5MI5V4hbg9u6rQuakhH35CNNoHGlY03ZHxoBUNyiMCvnohYoDFhCyXmH2NrewgZUJObkJ/CWmBEyhqpfL3wherOlyd00mxECWXkcPa7D5HyqODiyPKxpBbocqmyBZVXrbXT9yAuA72ke5fC55gOeSJA6X1rK2yZmA7ggmZmZIVRuoQCTWmi/32jiszuHjmeHoP9Dd6Riq3LsSHzGKATc7EiWkpoIUpBVmSkDO8h3WYB36k6wpkDswfqF4yuFikmYdM/feQqOQBirJP3gAr4EBqhii/3+WwUTlEPisDANMxuWLbWEysCwc87MPQ11ct5rvP42HTz7buP1hLWneyMUwsf6mD62mp0NdDS/wYfRWBpUCrYEr4PPlaA9mwm4dROusXrtP5PLlhLtGds3ZtClYzC84NveyEm6BN9svlgirJai
  template:
    metadata:
      name: mqtt-tailscale-auth
      namespace: mqtt
    type: Opaque
