---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zigbee2mqtt-auth
  namespace: mqtt
spec:
  encryptedData:
    username: AgB4coo3OD2FH7kSNU+Kbe5dL3dpkcEPENfl6YAFuNFmVbgDSMRu0HE1tXH3qgj/GShqRK/xnRaiExyyozGqFcPgar53SQZu3huyYsAXlr54f2jo6SJiWM7Jmt5VbEFsSc17mPK8hjuW9mg6HMICiT533AnLNC7sHmqwlU8bfd3twOYjz53JVuj50uUttMs6AWvV5PeuwWpP5THiqyiVEAJwzBdG9QsRxXvhQNUwbm/uSd+VhIFiBcnLvhix51fP/d57U5QDo5E2BB+sJJ7g2Jnes6427oPuzW3J6XAetTJgNuegpQGiJEgy3TbWXj88Ksfgoa5xMwDUaX5YadS0zrxZdbqXlA9rPQ23EzgjhxPqKz7hYUQ7jOixD+6kV3qAVeX3VK08lD4Ho5IJiEkrBc9aTZNq8IJN2Xr66UB0rzjUu1JdCjtsXMyvhKlMhpb+CUmexjEYFNeE6jz7/2v/mVwSXpTR2TmK/5ORaJXGR2kmVctDTk0tiDFa83HuwkCikXEPS77m1Dnk3vQAIFQwPQyVca+hPKJdtZdx6iVLO0dSnuRCiOF6v7GPTrHuioaG7z1RcKXFFHlA0RSydZXCyc4UmLDIn7svR3gzTbhU63dMnBgpWyncym6jbcy0nMwiGyb3yt8L1eL0uYDnq6krDjW3lP5Bs3kJI1F6jcXDOam5uqulJrQXO2+aawvvZqQuLHIwP9gBjaquCVVS5A==
    password: AgB+dm5SPyU57h2A/VjOlGPhRrgV1VfkYRuS83qDV6kYkEC3DxFPaA3urda0/0HSbtDrAj4tP4HfwitIUOoM2Mbh7ufk6LxloVMz2iBxcN3/uWbWuyChcPZ0rWsSrC4qcE0EUxgWyGbf8BkBeAvFBMjUcxfHwO1vASi41gS3qkFjrOBawZltoz4n24pRCQLphl5DRLofrSchJCVJSaprLmlw8zzrboHYVJ/sTJmXoW6rz3D4zKib2j2UwY5nV+q1Nv7CqUyaCCQZi6lmxW4uG6+iVSRMS338dGE4Y4EU/f5MC/qyWxT/aFnaF0UoTUJqxk7yj3EQizwSG3iTl3s/TABtlDm0KPFW0xGSgtVcAMzEjSlYdMMDFm1n/fs4BKlzkf17JOdcruXqoxBdTi9tCuvMRtQuZEGO7i+CiHSPHb/k2gdCJ9iHzFnPjnJ+gKtFv8xCtpnQoI07I9ysBeoDyjA1QNs+O79VF3T3adOl9h2WVXjnGAcYCk7DF4Riu9mW8RG1u0vS+kG5t7dAhS8nsMW9EBPUoyD+nqx9aeIY04aqyhqy5caATNOfrDBqw5HC/hVYnAtearuOOZJXBjeuAOiVdVpC8SUyxt7usnxmT+uDTKD2MzQdiAj2yS8/0vy0wNEn2eT5TOtrq/dtbkzkzeJ8YDWMZ8RhIsEfOuE4etQ/Fz19g2gFiIJtk3pm35zVn1KzrzRHF2ippQbO1viUrUuU1Nf/g//L7nN7w7GiRVJeF/FU1FgkLkHe3/Gc
  template:
    metadata:
      name: zigbee2mqtt-auth
      namespace: mqtt
    type: Opaque
