---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-tailscale-auth
  namespace: mqtt
spec:
  encryptedData:
    TS_AUTHKEY: AgChztXkdVtv/XOZCaVjCb/aBGLQvBe8b/ena0qzwRuDHmfuDWExaj/b1VSOdvjWimE+5+QGbiYV3FF+T1waPJiUUJ47HnUTMGvzFdT7Fyf52k5x7wI96R34n9gdtmn7T7fOJ8ZiGhxndvMO8SUW+IeF2pPITA9Jogby9L1CWDdxvBjczAm5aDyZWRow+xdHfvo6Xd/SaDRs286cW1+mVIBKj+KaLF84kpftjdbjHVHZeis/FLmE8q/Tm7n7M8nlI9XClAS+aKPez1Lgd70LU72kMUwln2xesEoT/haTXsxHNlhU5n2uKhNyjaql7KCk90fYRPLp3LA3atbP4V6nhBzWJIWrAvBTXGnxrU56HgH7JTqbQNTc7WbO7YkS/FLqtRqpinodXHi0b++tTrIM+wZuhritjJMLG7+2IvJuAqhwnho3I3XJLlFqz9k6wn+d7vcAB732Ql1HsmzUuvybDK+Jzzh48hyTaGR8t6I2/eId72xxIKLAgkX1IorpgLr9AOPio/GYr/kItSyizm8TFNzCogKuzOuGEICxK30fOyO6VznuzzI28g8ZQ8T8iOMC4bkAmzF5MsxTaPuCUSrM8If4un8EqyuxcaImhiIJ+ezJJLVv5deEsdD+dMnQHFWdgDzKKq/iWEXzBHmQZpU0EfFNoi7GzbHA03B6aUbkq6eVLux4iiL+a16WD4YbfyuLOqWdV9lRY68U7+xhi4E3maD2qeNmooVdwPjVOup6yH/eogtxp4tZfYV0Q9mY/mkmksu7/Gt2HFDKEGilL12fJZ/ziwR94uZclIZAkb+wtdWGT4jJO4n5lmsnUQ==
  template:
    metadata:
      name: mqtt-tailscale-auth
      namespace: mqtt
    type: Opaque
