---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zigbee2mqtt-auth
  namespace: mqtt
spec:
  encryptedData:
    username: AgBTiYyEDj1imHzilrkcQq5tYKstzoUXgK/6THIq3/RNTIVGdQnDXZnD6K2gj9gBy/DZosTZeTgFtzk5hsiduz4r1O34IdBgqBpBy9cnZ5aDGRVyAwiWDQbc/zEtYNnl5bvgYPdOyQvd3LqGN+UcrHKpUJxlhW5KA2SPTIMnJ6bACKbeeGkvb/ZhyZxpScJDn6KuSFKKeUVVUYtnhA8C0WRrzF7Qt+NWAKu2VMjA4Vueq3EXsuE2LQBm7kDal2cg/BXq9JbQ+KiaCCRd1G9482/yZbXijxaQNqFhTEgH/OTmMMM+r+3BtleOsyhk+sGllE41AKGXSVhs4L9b4nRN5NDguIKJ4OXGherzSt7IaW5DAkOwtGPmbP+4Vr6iDqoCIacaja7qlEBCQki+om2tYryC9RRI5eRA/2uVWp7ErxQFmwxY/OX94Y/XUkXLxltWVICF55vYdOamQldnC2dQcjBfOF3rhdv20cFxb4f4GDpoagR5pOn7+c9G9c5l9UL0803u6t2oIDbGWDQDlGuOEO/j5a7FPdiOOYHbtH+c+yOPgrRkj8p+iHP2OK+vKdFwK+W0JS4DDp/uRZwk1hPIrU8qe1E2di46baTTb0WBxSEq7BWWPWxUn3p7gak4Sjwzq40EpHjMOAwuHIH70iqKSHOk7D8LeJEPwn2Ew2n4VXefLki1iOHUec9PVDtUn6UXn11FJ3gVoDiYnRppjg==
    password: AgAN0Yv6xDo2lzYi67VhN8JEx41n3lKUNFsqVBCOJRuNn6Ktt/qgS5QLJyPigQ+Bwfyj/Vp2V/y2GMi7KZ7QCb8ABka9NZRl6Z1jGUlxNihzIxEXKSBv4wJsFwaCNPSB8JxUtmm5ncFTVDRSQ0coLqczLXBx9NEKN/owAjRYGfUuR4aBNChqI+1TFlFzXCdKw6igeNZS5VF3dUA+LWCFFYtNfQy3MkOwZkbVH2lBymknYgVLc1ikgBaShCjTvyehro2Me6vqFVBA0afCd+2bmLG5vFw8+OVmWwo2cfnC+NLm7tcEbdAMapyOpZY80cdlMX2Zwurj5AJcSIyC6+DT/HijnSgUFXDIkk75OkC5fvwEBtS6cDQAoKdJ3dFW+FKxF0Bhh2z4guB1M6RbVDwt4ARwkbzCJ/ul5keHSuwYdCuB2L07zJuXapkk6M+55cOYmM0fytiYG2HBcoeDXupr40IiJX36hebGS9RxyslmWM6EG+OpC9SYfqLx2ad45eP6FrZ0O0y1MlKn7uicPR5/lUwpFBc5N4D0K9WJv9v2Ado+IyzvbnlbufFFZZpPR7SB9hSiLpUNUi6Z6oxn7KL1NvaubOqAA6UjHf12YlCN0JPRFWFWbatpA+lVBsAhwSd3PMx17lcUzJuj5zv3nqubLWi+YpSRp2m4TTPJMvcm15uPdHo5+AdQLXvYGtheUcQ6U6pp55GFl+CUxSlDqre/tDC3vqP8A4/NX6iHhOQvS7qOj3+BnBXX379gjkdT
  template:
    metadata:
      name: zigbee2mqtt-auth
      namespace: mqtt
    type: Opaque
