---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-tailscale-auth
  namespace: mqtt
spec:
  encryptedData:
    TS_AUTHKEY: AgB0xH+ja6V7nML3d0f6WctX5S/qAoRTwjdPud338zYgo/C+ASQ6jmoSTUHBMAFNvsFSIIr/XNpn+DpyP5uHlAl5Nu4QcCPax+RAaS1A9A8MJOGpchNPTohswq9z2T+r/bdC3gKJbSw9Y4/UlpqSGckRLlkzCy0vGhsEQP26Ub9DNCMCA/Sprz3lbwSOWFlwCBToYj12Cos9kRPmsTE7WP61ruDZsr08F2sC+eIDbcFEBO54nB/6u6ikWRh5WqCtw2NxEgwRaPf5LyweC8R+BJkvCEvB3uD0VkuR9WFbTHKry82Zjo0eWO5Xj4lP4V5wLBPu7M4rnwxE90srBtZPhSS6YazxJ9OAbmHTdSiEZUGQ6XUpw4SsKgwNJh1dzZtPX6OfQECcoxj9Lf3OLOXrZp9U5ocY6TV1wcMZW1aRdunfrz2h6HqZrlBEliC5CWO+442QNcYM0itUDpjMi7OFZisFgovob+nonxrFc/iYdKkp508Vb7w33tdWgwNaZuOBSXfX1jzZEouaENG3rURx8IBPp2BarWSPiH9MZB0N7MnRHOq91YUF8FNwr+/GhYyUYS+5WErZrDjGZdWq0+A83WuKXgqejghD+7WbbTVHa0JB4QdDVDio5n+yBgfya+SIwRYxDQaT0Nc8Uk4Pgzi+SEhsyrfZ0JOtLaWQ36mwVQZJGFeBM259dDgEL4hTHk/nIv3BU9bMqHWvvkFLHGExaqWBNaAIn9PXAWnAtaMBkdTdvdGmeuurmVczzxAA8LKYIds/PyW2FSraRMCfPTs65twbnkssCbgAWAgvA/franRUUGq2oc5mGcsl
  template:
    metadata:
      name: mqtt-tailscale-auth
      namespace: mqtt
    type: Opaque
