---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: govee2mqtt-secrets
  namespace: mqtt
spec:
  encryptedData:
    GOVEE_EMAIL: AgBKervpL5NaWEXyaz4RX3clkrmgqhp9ytRh1TAlX4G/DERNHVaTfgWMlGLCbXtxQ1pdgKQtDuYF8Zh/AKQZQazU3iF4PiD7dCoxBC14cDrOtNF1CcOZLK2hfbqYHO8AoDCYN/rzxb9Q8BLJJ3GSZ1yN6vAoF9b+S759fuddFTLS2X3hPD3Jz1kJJScz0QTBUq81KEsx68+3daG+xdUjfGmpEzmwYijpC/CwCYPOdwdfrj538p+0/jJy1HWm/JcqfWR9KnxWcqbBA7W+v3pzMa+bMc5rl2vGT/4/wKwX8+qJ0NqZm+VDsVnuLbIDHhK4Q0dsgZwHSMgvrImMfRJH0tHGqw067cAComdOzVJG0hL6FUQV6MMNiV07B9WrVyPp2cZO+5y6HJCppJcp07/+0iDIybllsuWsvI7G8TLqIjQUsjlGkMXoFkQW19gW1IRpbIgwW2yZW3dyzeRBVJ65lgv50yJYfX6gE4umZk8BKbh0Qs5hq4/JjnEnFFa7HhnYoh1gQ9iJib93HqOIwkmbYpcbesvofMGmlt0vET7+nbCutThKgUk6dyhcfJ6oUKP39oU3Qg6bO2s1JC0MvCDVbzqyVTOkvfYo5O9SYVLzmyxuyIs0b2LpZP9Xx+lD10k1jo8hk8/Hu0YPT3OFauMD5AiJYVxbjXm2zcjhqryX3TppNPtg+w5cJUvlnAFymsWlkqcMPFZVAop0EeIeKjMSDdDjN2Gfgg==
    GOVEE_PASSWORD: AgAnWww5ePG7DK3pn5yueGTaYrjjRsoG2JpTfCYVZ/4J17tO6lZWZKqLhVDgJ6ENRkX7B/MEsI8zfpT5ug36l/EPxlpm1o5enojJGZmNoQYWih0gfV99sVEBViLWXJZGHNPG9v69ljdoLKTrEoV7efVLhoCKNaztHc5LqCChNR1G5ROv/LjeRDZ5+/yDAcdnYRM+Z37vhWOrRP1MKEN9OZdg/Z0ZUIr8jHOXXCAuFISkUxjm1BgPs0vHTuYm/hF4j0KBV23LcOZGZQKgSs0l7gVmqA+Y6z7iORLf28gBMXdN/xzKguIU4Pktpj3S3lLLY72VSMCkm1XpgESObdGrwlI6F6pUwzMc8V/7T20Y2B0Oodl69jK/c/pnSZ+CjRER+G9RqG8+iGDKsRH+X7H5Cn8/WGD4NLXddjZQmz+4d7QEmNwNAj85RLBDlgHhVFsnwEPhcA/wqgJ9Ywtu1vihXBPHxnl0BFn5s8vdBR/VVauaiCtM6QkEWDUBH0C3kBeuKFqR/NrMtGkaNn7YTfZW++VQyEE2gRV9xYmtPtzaXJZShIFp896nFSgAHvFC4YoBatyW8kGUZ/mveZ7/aCjHrmkIg+jX0YJNS+1djn1q7QzXw+RCkxtAReWlN5Egt6+vzr2nsm7998AuibZ3aWUbq+CGnHxdJDKIF27tkAEBGP6eCzGT2w8e6PcW5dp2gcwW9XZlpeOEZ9xvTN5/X/4=
  template:
    metadata:
      name: govee2mqtt-secrets
      namespace: mqtt
    type: Opaque
