---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-auth
  namespace: mqtt
spec:
  encryptedData:
    password: AgDCzpTqxxLZy1ms6ia72bwv3t96zY2hGJWgS5MDdqpbgUcaNatY6dN0hOnCwgRXZFVDj2+17xn7/ldJKk6Cyw0pbV36qXbm/0b2LcLIkHM4psRIJZnRONkX4skLE2Un2tAOAd+Te8i4aLkbPHnDzHm3ZzyOZMypTPkGbEkHFfrRjMJS6hmIZDVx269WwkY5gbtHoQI29zUQ0MFizplxrm/oVMPYpADXuOS7XYhpTTNOPvYdvfE428I8y8uWwjdAKAkq7QvobNyBg9vQprNz5D8y3EZ1JpvzNAKT98iuxoXSag8vazHsoEwZzvR7RwumSqsnA0bM4oy+jjeNZeNAIrpT8J0WeuTATAB+9QLJoS8cWmRgqXwTgFnnFNZzSom72MTTTVomO3YyjGrIMsM0a0zyqf5L84KWAoGR4/I3YZHYpZSw/Yg7/xsEWK/wQVKrfGbDnU2myUnfXRFAUD0SQgUKB3CRABg47a+em0aEkvLCzsJVS15dqrT5mYlzun3lTv+7eEuNaZnAaaoNfoElxe83c252udH0GpMlqAf3e/boosw9sEHLI+geoHycDYGsjn2M4gZKQqnqMPDek7WlrIJbEinxrsYeA/muHaRpiKtUVUDWytuzD+qQFabFNZE4xCksTRxKUYYhDH/iBK8hI7h1OlifjMkCVehP1MBnjXoE1zLsUJqI8V4v0JiG8TgW3XdXwomq8r6VPOjr9ZkmfIcJzQNfneSNXuEJuSDiDxGO2Q==
    username: AgASdGuOl5RuyRwnAxnIfbWb1bwBBOw0jUhBox84Qm0r+y7v3KjFxMnaIXbzM8BLAA1EczgupvT+F3/8s0gLYjIATfExCmgl/UUHyS4j6UWs6BefveAE2aaer5Va+MkoTF3vGLKJdE2UDVwk6OeR8MgNpI/RFBMe6X1KPRNf98qGgZaOV+0QXkw0Cl1D51FKe8dyV7oUfuP7qREqXVMrXLBs9FjcBsUAKHzJ8MxbXh6Frd+xdmFFuf0+ybwR2KiCR+pg+kF900W49poRCg2vlnbPA/dn8b+wP51OK4fN6kefwEChHQrXKj8p01j0mJXVT8dwyucCu7CKhtpV6Tw+/Ef4fG9Ttbp+khK7YiPHZV1+k2YwlDE2LzKkKbyw12JjW7TETdfNWbkdUPQ8U5wWyLucq7OI/5nf1o9xDuaMG/wSnVv6tFs+do4mTWMIEwQTbsqJ6oGRKWAmItZNcoQIkpO4vvHWXeyQslR7rFprXezizOS42gd8ACQ4q5wijpMoYryzzHXZenUZZOT0GDq+Li20xThr0OG/vrWX1oUNQ0Qq+tv58RHrt5O4DvSlFlwuS/gY8LU2NdP2oGL0UU1up3qzBl8+U2nWR5SSAZlx92VTKUvQMkojz1aUc3YGhxKv7tMTOQccCh3YVmCj6YulNjRdLneFdbDG/af5xqMSAxqmlJYgsaexYH/4vNXm7Bu4Po5LoFJ10mA3IeYdoZq6
  template:
    metadata:
      name: mqtt-auth
      namespace: mqtt
    type: Opaque
