---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: mqtt
  labels:
    app: mqtt
spec:
  selector:
    app: mqtt
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
