---
# Shared Media PVC
# Used by Jellyfin, Sonarr, Radarr, Bazarr for media files
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: media-storage
  labels:
    app.kubernetes.io/name: media-storage
    storage-type: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-media
  resources:
    requests:
      storage: 2Ti
---
# Shared Downloads PVC
# Used by qBittorrent/SABnzbd for temporary downloads
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: media-storage
  labels:
    app.kubernetes.io/name: media-storage
    storage-type: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-downloads
  resources:
    requests:
      storage: 500Gi
