---
# SealedSecret for ArgoCD OIDC
# Contains Pocket ID client secret
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
spec:
  encryptedData:
    # Pocket ID OIDC client secret - referenced as $oidc.pocketid.clientSecret in argocd-cm
    oidc.pocketid.clientSecret: AgCuR+rqanxfkMzei4nxC1jGkuuEeqMKPkMhtM1WtIIcGk9sa/E2l8WZLVEdd/CZaJ8Fay+A5fyBJ+PSo1H8Wr24oVj6T65ncLExjn397dyAK0CbbUfHcDI5BLYVwJgRpTlge7cCHu92HEWdAB/gSXQos4T9xkAAon7ZfZsDyx9qL2KjYejgF7v9C28d4z+GdKZ/phKPOxua53xRhWKO3tLbFSSVCUEWgcGub69/hfroMPhy0vEnoydk9QMKmQbkRclulxP0sX8vcD5ARNQS1Cc5cxbG1uQMD+uHTD2YtFYRMfHISgBux1s8R/s/3zT4m2Vq9+mTGtUnPe+gNCn5JucmPa9YTXL7uDnrTTUGlBZPT2j+XSQBphYAL/Ykyo5zJzPVHlyedZNuXr53QO0V5ScSQt2/lTD6qp/sjkonNxCMZHRqKUIT/LDZ5x+6G+JEe+gafjCgekU1AF+2psPV2srQTxZ8b4lXB/xO3rW2O7GqOqd7CUZWWaRJVTQ7nGjEMnVXdLMZitxJC6gl7STVv65v0y+QDN6LvO9i9XPZ/C3hAAcGwN/FIdPYaPkWRB064hiyySiw6QT59238j5BPSlykoud4bF/1p1+Zg1CneHpaG7NdctLJBUOEdwLLZq6lbORaUu5VcjUBDR7lGik3iiMXY6xaU7YogeARf9iDF/fPS54oQ03aT14PSlrBmOdpp0To8thCzlnA+5GX3iKX6QrRfNHsRHIHr6+4W/wgMLSqPn7I86XikCCXbODaJA==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
    type: Opaque
