---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unpoller-secret
  namespace: unpoller
spec:
  encryptedData:
    password: AgA6+Vfjh2ysRAm+E0163gv7SuMYU+uECPnnf0GFfrAHhTQ2bxyMV22wtcHLOBJVrQqiO2m5YkvMgpnZ/34wGbtI1khTqNRW6/qxnqO6bObFapX8HKf0BDxMyYurPSxmdOHRkCgJBq39pkik/k642zNnwsF7CvU2NDl3htCyt2Snm/Bie/7lIN2TU6+OCNaSTRqzvfUMSzu+wMW2ZrzniKlJCtxfxctJxduzZ29QmjaSY6kACBwNnht63W3srh0G0Xt6xAlq3MJCxkr0/7kLs8g7NDDxS4KUmuKDb2/dp3/b9POAMbg/q8cmx2cRa8SImC58nOheiYfFKJBNx/lP/t/7t16xemAiQuHPwU852qFoSCSI1dDOpzbcZMDyL2OQsiVwhgGEGc5aa8siwm35N5jLWD11Syq4lYDRW7f21AXN+J6SiLibjCLYjo6h87VbHdKJrg37OqmL5hg60b3OxI4AZ9WqH9/iTERXwNgFK9RMARXcRRH7veJ+bhSErblz81EZ9HDxG65RED29pruar/V4Fwp6oW08k+NgsrBWQ+fk8pVQxa7gdx6Chwk8NdeOEGPJCmsRAYcehs5J6wo/bfFid37O2M+GBJsLszNRYW0ZEy66u2Xoh+o9jyDBqq4sfMu778jyh92+/j/mrd4KBho9k/ru1mpSMvFFwo/jx5A47EmQ1WCbx+NHftim/00ArnaRGh3ZmMBgw9D2/8acS/6qJkdf6A==
  template:
    metadata:
      name: unpoller-secret
      namespace: unpoller
    type: Opaque
